"""Adding  column to FileWidget table

Revision ID: 00dddde76cd0
Revises: 51698c44bdff
Create Date: 2024-06-27 15:51:52.553953

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "00dddde76cd0"
down_revision = "51698c44bdff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_widget", sa.Column("source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_widget", "source")
    # ### end Alembic commands ###
