"""Switch content from GZIP to JSON

Revision ID: 026bdc3ded4d
Revises: 4ba2b889e403
Create Date: 2023-11-17 10:56:08.908586

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "026bdc3ded4d"
down_revision = "4ba2b889e403"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dashboard_item",
        "content",
        existing_type=sa.BLOB(),
        type_=sa.JSON(),
        existing_nullable=True,
        postgresql_using="convert_from(content, 'UTF8')::json",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dashboard_item",
        "content",
        existing_type=sa.JSON(),
        type_=sa.BLOB(),
        existing_nullable=True,
        postgresql_using="content::text::bytea",
    )
    # ### end Alembic commands ###
