"""Final user fields

Revision ID: 04c0080fee5a
Revises: 6fe17636f05a
Create Date: 2023-03-15 10:46:44.259049

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "04c0080fee5a"
down_revision = "6fe17636f05a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("other_student_field", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("fund_name", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("club_name", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("society_name", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("explain_investment_club", sa.Text(), nullable=True))
    op.drop_column("user", "organization_name")
    op.drop_column("user", "fund_club_intro")
    op.drop_column("user", "market_focus")
    op.drop_column("user", "investment_community")
    op.drop_column("user", "how_we_help")
    op.drop_column("user", "discusses")
    op.drop_column("user", "asset_classes")
    op.drop_column("user", "university_intro")
    op.drop_column("user", "finance_market")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("finance_market", sa.TEXT(collation="utf8mb4_unicode_ci"), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "university_intro",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column("asset_classes", sa.TEXT(collation="utf8mb4_unicode_ci"), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("discusses", sa.TEXT(collation="utf8mb4_unicode_ci"), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("how_we_help", sa.TEXT(collation="utf8mb4_unicode_ci"), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "investment_community",
            sa.TEXT(collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column("market_focus", sa.TEXT(collation="utf8mb4_unicode_ci"), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "fund_club_intro",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "organization_name",
            sa.TEXT(collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
    )
    op.drop_column("user", "explain_investment_club")
    op.drop_column("user", "society_name")
    op.drop_column("user", "club_name")
    op.drop_column("user", "fund_name")
    op.drop_column("user", "other_student_field")
    # ### end Alembic commands ###
