"""add socials to user

Revision ID: 0a1ccb6a2e03
Revises: 60219005d82d
Create Date: 2023-08-04 07:41:17.610428

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "0a1ccb6a2e03"
down_revision = "60219005d82d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("discord", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("twitter", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("linkedin", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("telegram", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "telegram")
    op.drop_column("user", "linkedin")
    op.drop_column("user", "twitter")
    op.drop_column("user", "discord")
    # ### end Alembic commands ###
