"""Add dashboard item

Revision ID: 0adbf87d25e9
Revises: 2b450b3a50b8
Create Date: 2023-07-31 10:48:18.066172

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime

# revision identifiers, used by Alembic.
revision = "0adbf87d25e9"
down_revision = "2b450b3a50b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_item",
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboard_item")
    # ### end Alembic commands ###
