"""add slug column to script

Revision ID: 0ea2826f648a
Revises: 64c92d07af72
Create Date: 2023-08-11 08:37:32.576952

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "0ea2826f648a"
down_revision = "64c92d07af72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feature",
        "votes",
        existing_type=sa.INTEGER().with_variant(mysql.INTEGER(display_width=11), "mysql"),
        nullable=False,
    )
    op.add_column("script", sa.Column("slug", sa.VARCHAR(200), nullable=True))
    op.alter_column(
        "script",
        "public",
        existing_type=sa.Boolean(),
        nullable=False,
    )
    op.create_unique_constraint("slug_user_id_unique", "script", ["slug", "user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("slug_user_id_unique", "script", type_="unique")
    op.alter_column(
        "script",
        "public",
        existing_type=sa.Boolean(),
        nullable=True,
    )
    op.drop_column("script", "slug")
    op.alter_column(
        "feature",
        "votes",
        existing_type=sa.INTEGER().with_variant(mysql.INTEGER(display_width=11), "mysql"),
        nullable=True,
    )
    # ### end Alembic commands ###
