"""chargbee model

Revision ID: 0fc20d03e5f7
Revises: dee2a485b94b
Create Date: 2022-06-08 09:25:36.234522

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "0fc20d03e5f7"
down_revision = "dee2a485b94b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chargebee",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("customer_id", sa.String(length=100), nullable=True),
        sa.Column("customer_email", sa.String(length=100), nullable=True),
        sa.Column("payment_type", sa.String(length=100), nullable=True),
        sa.Column("payment_reference_id", sa.String(length=100), nullable=True),
        sa.Column("payment_gateway", sa.String(length=100), nullable=True),
        sa.Column("invoice_id", sa.String(length=100), nullable=True),
        sa.Column("invoice_date", sa.DateTime(), nullable=True),
        sa.Column("invoice_due_date", sa.DateTime(), nullable=True),
        sa.Column("invoice_amount_paid", sa.String(length=100), nullable=True),
        sa.Column("invoice_total", sa.String(length=100), nullable=True),
        sa.Column("invoice_paid_at", sa.DateTime(), nullable=True),
        sa.Column("subscription_id", sa.String(length=100), nullable=True),
        sa.Column("subscription_billing_period", sa.String(length=100), nullable=True),
        sa.Column("subscription_billing_period_unit", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "charge_plan",
        sa.Column("chargebee_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("plan_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chargebee_uuid"],
            ["chargebee.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_uuid"],
            ["plan.uuid"],
        ),
        sa.PrimaryKeyConstraint("chargebee_uuid", "plan_uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("charge_plan")
    op.drop_table("chargebee")
    # ### end Alembic commands ###
