"""FIxed issues

Revision ID: 0ffea848800c
Revises: 44317fee32e8
Create Date: 2023-03-09 09:29:43.098753

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "0ffea848800c"
down_revision = "44317fee32e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("features_sources", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "features_sources")
    # ### end Alembic commands ###
