"""unique user_uuid and nullable disabled_widgets

Revision ID: 12e8a1168bad
Revises: f4719449c6ba
Create Date: 2024-09-02 11:58:07.325867

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "12e8a1168bad"
down_revision = "f4719449c6ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "enabled_widget_bundles",
        "disabled_widgets",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.create_unique_constraint(None, "enabled_widget_bundles", ["user_uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "enabled_widget_bundles", type_="unique")
    op.alter_column(
        "enabled_widget_bundles",
        "disabled_widgets",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    # ### end Alembic commands ###
