"""Add profile pic bool

Revision ID: 16d586938d51
Revises: f098e52ff468
Create Date: 2023-05-18 15:53:01.115789

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "16d586938d51"
down_revision = "f098e52ff468"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("has_profile_url", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_profile_url")
    # ### end Alembic commands ###
