"""add entity_uuid to DashboardItem

Revision ID: d6ce3fbaec7d
Revises: f1317bfd4f67
Create Date: 2024-10-08 11:56:10.607308

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "d6ce3fbaec7d"
down_revision = "f1317bfd4f67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dashboard_item",
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    )
    op.create_index(
        op.f("ix_dashboard_item_entity_share"),
        "dashboard_item",
        ["entity_share"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboard_item_entity_uuid"),
        "dashboard_item",
        ["entity_uuid"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_dashboard_item_entity_uuid_entity"),
        "dashboard_item",
        "entity",
        ["entity_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_dashboard_item_entity_uuid_entity"),
        "dashboard_item",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_dashboard_item_entity_uuid"), table_name="dashboard_item")
    op.drop_index(op.f("ix_dashboard_item_entity_share"), table_name="dashboard_item")
    op.drop_column("dashboard_item", "entity_uuid")
    # ### end Alembic commands ###
