"""add pro_trial_granted

Revision ID: 923d0c303d95
Revises: d6ce3fbaec7d
Create Date: 2024-10-21 15:35:25.153609

"""

import sqlalchemy as sa

from alembic import op
from api.models.model_helpers import AwareDateTime  # type: ignore

# revision identifiers, used by Alembic.
revision = "923d0c303d95"
down_revision = "d6ce3fbaec7d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("pro_trial_granted", sa.Boolean(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "pro_trial_granted_date",
            AwareDateTime(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pro_trial_granted")
    op.drop_column("user", "pro_trial_granted_date")
    # ### end Alembic commands ###
