"""add stored_file_share

Revision ID: 5ce723a30834
Revises: 923d0c303d95
Create Date: 2024-10-28 13:31:05.746024

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models.model_helpers import AwareDateTime  # type: ignore

# revision identifiers, used by Alembic.
revision = "5ce723a30834"
down_revision = "2bb3f9359253"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_file_share",
        sa.Column(
            "dashboard_item_uuid",
            sqlalchemy_utils.types.uuid.UUIDType(),
            nullable=False,
        ),
        sa.Column("creater_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("shared_user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "stored_file_uuids",
            sqlalchemy_utils.types.scalar_list.ScalarListType(),
            nullable=False,
        ),
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creater_uuid"],
            ["user.uuid"],
            name=op.f("fk_stored_file_share_creater_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["dashboard_item_uuid"],
            ["dashboard_item.uuid"],
            name=op.f("fk_stored_file_share_dashboard_item_uuid_dashboard_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_stored_file_share_entity_uuid_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["shared_user_uuid"],
            ["user.uuid"],
            name=op.f("fk_stored_file_share_shared_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_stored_file_share_creater_uuid"),
        "stored_file_share",
        ["creater_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_file_share_dashboard_item_uuid"),
        "stored_file_share",
        ["dashboard_item_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_file_share_entity_uuid"),
        "stored_file_share",
        ["entity_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_file_share_shared_user_uuid"),
        "stored_file_share",
        ["shared_user_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_dashboard_share_active"), "dashboard_share", ["active"], unique=False)
    op.create_index(op.f("ix_dashboard_share_viewed"), "dashboard_share", ["viewed"], unique=False)
    op.add_column("stored_file", sa.Column("is_entity_shared", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_stored_file_creater_uuid"),
        "stored_file",
        ["creater_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_file_file_widget_uuid"),
        "stored_file",
        ["file_widget_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_file_is_entity_shared"),
        "stored_file",
        ["is_entity_shared"],
        unique=False,
    )
    op.create_index(op.f("ix_stored_file_is_global"), "stored_file", ["is_global"], unique=False)
    op.create_foreign_key(
        op.f("fk_widget_metadata_user_uuid_user"),
        "widget_metadata",
        "user",
        ["user_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_widget_metadata_user_uuid_user"), "widget_metadata", type_="foreignkey")
    op.drop_index(op.f("ix_stored_file_is_global"), table_name="stored_file")
    op.drop_index(op.f("ix_stored_file_is_entity_shared"), table_name="stored_file")
    op.drop_index(op.f("ix_stored_file_file_widget_uuid"), table_name="stored_file")
    op.drop_index(op.f("ix_stored_file_creater_uuid"), table_name="stored_file")
    op.drop_column("stored_file", "is_entity_shared")
    op.drop_index(op.f("ix_dashboard_share_viewed"), table_name="dashboard_share")
    op.drop_index(op.f("ix_dashboard_share_active"), table_name="dashboard_share")
    op.drop_index(op.f("ix_stored_file_share_shared_user_uuid"), table_name="stored_file_share")
    op.drop_index(op.f("ix_stored_file_share_entity_uuid"), table_name="stored_file_share")
    op.drop_index(op.f("ix_stored_file_share_dashboard_item_uuid"), table_name="stored_file_share")
    op.drop_index(op.f("ix_stored_file_share_creater_uuid"), table_name="stored_file_share")
    op.drop_table("stored_file_share")
    # ### end Alembic commands ###
