"""update tier defaults and bundle values

Revision ID: a54ccee370c4
Revises: 5ce723a30834
Create Date: 2024-11-04 13:17:23.346449

"""

import sqlalchemy as sa

from alembic import op
from api.models.tier_models import DataBundle  # type: ignore

# revision identifiers, used by Alembic.
revision = "a54ccee370c4"
down_revision = "5ce723a30834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        sa.update(DataBundle)
        .where(DataBundle.bundle_name == "Default")
        .values(
            except_widgets='["etf_holdings", "economic_calendar", "earnings_trends", "revenue_trends", "etf_classification", "etf_characteristics"]',
            except_dashboard_templates='["etfTemplate"]',
            except_team_collaboration='["pdf_reports", "sharing"]',
            excel_add_in=0,
            data_export=0,
            providers='["fmp", "econdb", "benzinga"]',
            dashboards_at_launch='["onboarding", "charting", "news", "equity", "equityAnalyst", "calendars"]',
            my_dashboards='["onboarding", "news", "charting", "equity", "equityAnalyst", "calendars", "countryEconomics"]',
            invite_your_colleagues=1,
            number_copilot_calls_day=20,
            total_file_upload_size_gb=1,
        )
    )

    op.execute(
        sa.update(DataBundle)
        .where(DataBundle.bundle_name == "Equity Research")
        .values(
            except_widgets="[]",
            except_dashboard_templates="[]",
            except_team_collaboration=None,
            excel_add_in=1,
            data_export=1,
            providers=None,
            dashboards_at_launch='["onboarding", "charting", "news", "equity", "analyst", "calendars", "etfTemplate"]',
            my_dashboards='["onboarding", "news", "charting", "equity", "equityAnalyst", "calendars", "countryEconomics"]',
            invite_your_colleagues=0,
            number_copilot_calls_day=100,
            total_file_upload_size_gb=10,
        )
    )

    op.execute(
        sa.update(DataBundle)
        .where(DataBundle.bundle_name == "Pro Trial")
        .values(
            except_widgets='["etf_holdings", "economic_calendar", "earnings_trends", "revenue_trends", "etf_classification", "etf_characteristics"]',
            except_dashboard_templates='["etfTemplate"]',
            except_team_collaboration=None,
            excel_add_in=1,
            data_export=1,
            providers='["fmp", "econdb", "benzinga"]',
            dashboards_at_launch='["onboarding", "charting", "news", "equity", "equityAnalyst", "calendars"]',
            my_dashboards='["onboarding", "news", "charting", "equity", "equityAnalyst", "calendars", "countryEconomics"]',
            invite_your_colleagues=0,
            number_copilot_calls_day=100,
            total_file_upload_size_gb=10,
        )
    )

    op.execute(
        """
    UPDATE default_tier
    SET
        total_file_upload_size_gb = 100
    WHERE
        name = 'ProDefaults';
    """
    )

    op.execute(
        """
        UPDATE entity_entitlement
        SET
            data_bundle_uuid =
                (select uuid from data_bundle where bundle_name = 'Pro Trial' limit 1)
        WHERE
            entity_uuid =
                (select uuid from entity where name = 'OpenBB Trial' limit 1);
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # since those tables hold constant values, we won't downgrade them
    pass

    # ### end Alembic commands ###
