"""remove identifier column from custom copilot table

Revision ID: 796c4a733b6a
Revises: 598a7e069001
Create Date: 2024-11-18 18:52:51.391126

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "796c4a733b6a"
down_revision = "598a7e069001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    if dialect == "mysql":
        op.drop_index("uix_user_copilot", table_name="custom_copilot")
    elif dialect == "postgresql":
        op.drop_constraint("uix_user_copilot", "custom_copilot", type_="unique")

    op.create_unique_constraint("uix_user_url_custom_copilot", "custom_copilot", ["user_uuid", "url"])
    op.drop_column("custom_copilot", "copilot_identifier")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_copilot",
        sa.Column("copilot_identifier", sa.VARCHAR(length=50), nullable=False),
    )
    op.drop_constraint("uix_user_url_custom_copilot", "custom_copilot", type_="unique")
    op.create_index(
        "uix_user_copilot",
        "custom_copilot",
        ["user_uuid", "copilot_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###
