"""add custom copilot table

Revision ID: 598a7e069001
Revises: 923d0c303d95
Create Date: 2024-11-18 16:12:37.801033

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "598a7e069001"
down_revision = "923d0c303d95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_copilot",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("copilot_identifier", sa.String(50), nullable=False),
        sa.Column("url", sa.String(200), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("fk_custom_copilot_user_uuid_user")),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "copilot_identifier", name="uix_user_copilot"),
    )
    op.create_index(
        op.f("ix_custom_copilot_user_uuid"),
        "custom_copilot",
        ["user_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_custom_copilot_user_uuid"), table_name="custom_copilot")
    op.drop_table("custom_copilot")
    # ### end Alembic commands ###
