"""add welcome_scrren col to user

Revision ID: 2bb3f9359253
Revises: 14c119f8704c
Create Date: 2024-11-26 14:38:12.918200

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "2bb3f9359253"
down_revision = "14c119f8704c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("welcome_screen", sa.Boolean(), default=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "welcome_screen")
    # ### end Alembic commands ###
