"""add skip_onboarding column

Revision ID: 14c119f8704c
Revises: 2b2e8f609db1
Create Date: 2024-11-26 11:23:58.527273

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "14c119f8704c"
down_revision = "2b2e8f609db1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "developer_onboarding",
        sa.Column("skip_onboarding", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("developer_onboarding", "skip_onboarding")
    # ### end Alembic commands ###
