"""make column headers encrypted on custom copilots table

Revision ID: e7bc1dccaef8
Revises: 796c4a733b6a
Create Date: 2024-11-20 09:37:38.751029

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import EncryptedType

# revision identifiers, used by Alembic.
revision = "e7bc1dccaef8"
down_revision = "796c4a733b6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_copilot",
        "headers",
        existing_type=sa.JSON(),
        type_=EncryptedType(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_copilot",
        "headers",
        existing_type=EncryptedType(),
        type_=sa.JSON(),
        nullable=False,
    )
    # ### end Alembic commands ###
