"""make column headers encrypted on api_source

Revision ID: 2b2e8f609db1
Revises: e7bc1dccaef8
Create Date: 2024-11-20 11:12:45.477810

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import EncryptedType

# revision identifiers, used by Alembic.
revision = "2b2e8f609db1"
down_revision = "e7bc1dccaef8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_source",
        "endpointHeaders",
        existing_type=sa.JSON(),
        type_=EncryptedType(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_source",
        "endpointHeaders",
        existing_type=EncryptedType(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
