"""update data bundle values

Revision ID: 83657cdd4ce9
Revises: a54ccee370c4
Create Date: 2024-12-06 14:06:15.571685

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.tier_models import DataBundle

# revision identifiers, used by Alembic.
revision = "83657cdd4ce9"
down_revision = "a54ccee370c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        sa.update(DataBundle)
        .where(DataBundle.bundle_name == "Pro Trial")
        .values(
            except_widgets="[]",
            except_dashboard_templates="[]",
            except_team_collaboration="[]",
            excel_add_in=1,
            data_export=1,
            providers=None,
            dashboards_at_launch='["onboarding", "charting", "news", "equity", "equityAnalyst", "calendars", "etfTemplate"]',
            my_dashboards='["onboarding", "news", "charting", "equity", "equityAnalyst", "calendars", "countryEconomics"]',
            invite_your_colleagues=0,
            number_copilot_calls_day=100,
            total_file_upload_size_gb=100,
        )
    )

    op.execute(
        sa.update(DataBundle)
        .where(DataBundle.bundle_name == "Equity Research")
        .values(
            except_widgets="[]",
            except_dashboard_templates="[]",
            except_team_collaboration="[]",
            excel_add_in=1,
            data_export=1,
            providers=None,
            dashboards_at_launch='["onboarding", "charting", "news", "equity", "equityAnalyst", "calendars", "etfTemplate"]',
            my_dashboards='["onboarding", "news", "charting", "equity", "equityAnalyst", "calendars", "countryEconomics"]',
            invite_your_colleagues=0,
            number_copilot_calls_day=100,
            total_file_upload_size_gb=10,
        )
    )
    op.execute(
        sa.update(DataBundle)
        .where(DataBundle.bundle_name == "Default")
        .values(
            except_widgets='["etf_holdings", "economic_calendar", "earnings_trends", "revenue_trends", "etf_classification", "etf_characteristics"]',
            except_dashboard_templates='["etfTemplate"]',
            except_team_collaboration='["pdf_reports", "sharing"]',
            excel_add_in=0,
            data_export=0,
            providers='["fmp", "econdb", "benzinga"]',
            dashboards_at_launch='["onboarding", "charting", "news", "equity", "equityAnalyst", "calendars"]',
            my_dashboards='["onboarding", "news", "charting", "equity", "equityAnalyst", "calendars", "countryEconomics"]',
            invite_your_colleagues=1,
            number_copilot_calls_day=20,
            total_file_upload_size_gb=1,
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
