"""add hear_about_us column to user

Revision ID: 4757eae934b4
Revises: 83657cdd4ce9
Create Date: 2025-01-02 11:14:00.388637

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "4757eae934b4"
down_revision = "83657cdd4ce9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hear_about_us", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hear_about_us")
    # ### end Alembic commands ###
