"""add youtube type to metadata

Revision ID: 9f7abb800ab8
Revises: 4757eae934b4
Create Date: 2025-01-02 17:07:35.823329

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "9f7abb800ab8"
down_revision = "4757eae934b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("widget_type_check", "widget_metadata", type_="check")
    op.create_check_constraint(
        "widget_type_check",
        "widget_metadata",
        "widget_type IN ('iframe', 'rss_viewer', 'rich_note', 'copilot_table', 'youtube')",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("widget_type_check", "widget_metadata", type_="check")
    op.create_check_constraint(
        "widget_type_check",
        "widget_metadata",
        "widget_type IN ('iframe', 'rss_viewer', 'rich_note', 'copilot_table')",
    )
    # ### end Alembic commands ###
