"""add tv layouts

Revision ID: e8ed217393f5
Revises: 9f7abb800ab8
Create Date: 2025-01-07 10:22:04.821920

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime, GzipJsonType

# revision identifiers, used by Alembic.
revision = "e8ed217393f5"
down_revision = "9f7abb800ab8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_view",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("charts_state", GzipJsonType(), nullable=False),
        sa.Column("settings", GzipJsonType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("fk_trading_view_user_uuid_user")),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trading_view")
    # ### end Alembic commands ###
