"""change prompt state column to gzip

Revision ID: a639db1f2d56
Revises: b0c4f34c0b8f
Create Date: 2025-01-13 12:31:37.822166

"""

import sqlalchemy as sa

from alembic import op
from api.models.model_helpers import GzipJsonType  # type: ignore

# revision identifiers, used by Alembic.
revision = "a639db1f2d56"
down_revision = "b0c4f34c0b8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_prompts",
        "prompt",
        existing_type=sa.JSON(),
        type_=GzipJsonType(),
        existing_nullable=True,
        postgresql_using="prompt::text::bytea",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_prompts",
        "prompt",
        existing_type=GzipJsonType(),
        type_=sa.JSON(),
        existing_nullable=True,
        postgresql_using="convert_from(decode(prompt::text, 'escape'), 'UTF8')::json",
    )
    # ### end Alembic commands ###
