"""remove allowed users column

Revision ID: 0852f601688b
Revises: 18603b3fd776
Create Date: 2025-01-09 08:05:14.486780

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "0852f601688b"
down_revision = "18603b3fd776"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity_prompts", "allowed_users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity_prompts", sa.Column("allowed_users", sa.JSON(), nullable=False))
    # ### end Alembic commands ###
