"""make prompt a JSON - represents the user state

Revision ID: b0c4f34c0b8f
Revises: cdd8cf5a4654
Create Date: 2025-01-13 11:25:53.824296

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "b0c4f34c0b8f"
down_revision = "cdd8cf5a4654"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_prompts",
        "prompt",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        nullable=True,
        postgresql_using="prompt::json",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_prompts",
        "prompt",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=False,
        postgresql_using="prompt::text",
    )
    # ### end Alembic commands ###
