"""add user and entity prompt tables

Revision ID: 18603b3fd776
Revises: 4757eae934b4
Create Date: 2025-01-09 07:13:20.277078

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "18603b3fd776"
down_revision = "4757eae934b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_prompts",
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("allowed_users", sa.JSON(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_entity_prompts_entity_uuid_entity"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_entity_prompts_entity_uuid"),
        "entity_prompts",
        ["entity_uuid"],
        unique=False,
    )
    op.create_table(
        "user_prompts",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("fk_user_prompts_user_uuid_user")),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_user_prompts_user_uuid"), "user_prompts", ["user_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_prompts_user_uuid"), table_name="user_prompts")
    op.drop_table("user_prompts")
    op.drop_index(op.f("ix_entity_prompts_entity_uuid"), table_name="entity_prompts")
    op.drop_table("entity_prompts")
    # ### end Alembic commands ###
