"""add two_factor_auth column

Revision ID: d64ba58254b9
Revises: a639db1f2d56
Create Date: 2025-01-20 12:25:45.004447

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "d64ba58254b9"
down_revision = "a639db1f2d56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("two_factor_auth", sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "two_factor_auth")
    # ### end Alembic commands ###
