"""add templates column

Revision ID: 93ea453bc967
Revises: 47e64de16d37
Create Date: 2025-02-07 12:25:44.903204

"""

import sqlalchemy as sa

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "93ea453bc967"
down_revision = "47e64de16d37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role_backend",
        sa.Column("templates", api.models.model_helpers.GzipJsonType(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_backend", "templates")
    # ### end Alembic commands ###
