"""add access column

Revision ID: 833cfa69f6b7
Revises: 12607d7437b8
Create Date: 2025-02-05 16:32:44.740429

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "833cfa69f6b7"
down_revision = "12607d7437b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("role_backend", sa.Column("access", sa.String(length=100), nullable=False))
    op.add_column("role_file", sa.Column("access", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_file", "access")
    op.drop_column("role_backend", "access")
    # ### end Alembic commands ###
