"""cascade delete for user_group table: on group deletion

Revision ID: 75ad2dd38c07
Revises: 2d5abe125ef6
Create Date: 2025-02-04 07:53:34.750970

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "75ad2dd38c07"
down_revision = "2d5abe125ef6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_group_entity_name", "group", ["entity_uuid", "name"])
    op.drop_constraint("fk_user_group_group_uuid_group", "user_group", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_user_group_group_uuid_group"),
        "user_group",
        "group",
        ["group_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_user_group_group_uuid_group"), "user_group", type_="foreignkey")
    op.create_foreign_key(
        "fk_user_group_group_uuid_group",
        "user_group",
        "group",
        ["group_uuid"],
        ["uuid"],
    )
    op.drop_constraint("uix_group_entity_name", "group", type_="unique")
    # ### end Alembic commands ###
