"""on delete cascade for file and backend associated with given roles

Revision ID: 5cc5eea61ec4
Revises: 93ea453bc967
Create Date: 2025-02-07 12:32:52.956954

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "5cc5eea61ec4"
down_revision = "93ea453bc967"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_role_backend_role_uuid_role", "role_backend", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_backend_role_uuid_role"),
        "role_backend",
        "role",
        ["role_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_role_file_role_uuid_role", "role_file", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_file_role_uuid_role"),
        "role_file",
        "role",
        ["role_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_role_file_role_uuid_role"), "role_file", type_="foreignkey")
    op.create_foreign_key("fk_role_file_role_uuid_role", "role_file", "role", ["role_uuid"], ["uuid"])
    op.drop_constraint(op.f("fk_role_backend_role_uuid_role"), "role_backend", type_="foreignkey")
    op.create_foreign_key(
        "fk_role_backend_role_uuid_role",
        "role_backend",
        "role",
        ["role_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###
