"""add widegts colum to role_backend

Revision ID: 47e64de16d37
Revises: 833cfa69f6b7
Create Date: 2025-02-06 10:29:56.101977

"""

import sqlalchemy as sa

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "47e64de16d37"
down_revision = "833cfa69f6b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role_backend",
        sa.Column("widgets", api.models.model_helpers.GzipJsonType(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_backend", "widgets")
    # ### end Alembic commands ###
