"""role_file and role_backend tables

Revision ID: 12607d7437b8
Revises: e337419ca6a7
Create Date: 2025-02-05 16:08:38.195568

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "12607d7437b8"
down_revision = "e337419ca6a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_backend",
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("backend_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backend_uuid"],
            ["api_source.uuid"],
            name=op.f("fk_role_backend_backend_uuid_api_source"),
        ),
        sa.ForeignKeyConstraint(["role_uuid"], ["role.uuid"], name=op.f("fk_role_backend_role_uuid_role")),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_role_backend_backend_uuid"),
        "role_backend",
        ["backend_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_role_backend_role_uuid"), "role_backend", ["role_uuid"], unique=False)
    op.create_table(
        "role_file",
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("file_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_uuid"],
            ["file_widget.uuid"],
            name=op.f("fk_role_file_file_uuid_file_widget"),
        ),
        sa.ForeignKeyConstraint(["role_uuid"], ["role.uuid"], name=op.f("fk_role_file_role_uuid_role")),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_role_file_file_uuid"), "role_file", ["file_uuid"], unique=False)
    op.create_index(op.f("ix_role_file_role_uuid"), "role_file", ["role_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_file_role_uuid"), table_name="role_file")
    op.drop_index(op.f("ix_role_file_file_uuid"), table_name="role_file")
    op.drop_table("role_file")
    op.drop_index(op.f("ix_role_backend_role_uuid"), table_name="role_backend")
    op.drop_indsx(op.f("ix_role_backend_backend_uuid"), table_name="role_backsend")
    op.drop_table("role_backend")
    # ### end Alembic commands ###
