"""make entity name unique

Revision ID: 50a057621532
Revises: d64ba58254b9
Create Date: 2025-01-30 17:44:33.056774

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "50a057621532"
down_revision = "d64ba58254b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "entity", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "entity", type_="unique")
    # ### end Alembic commands ###
