"""make widgets and templates column nullable on

Revision ID: 3497d4c95cf9
Revises: 5cc5eea61ec4
Create Date: 2025-02-07 13:04:10.150572

"""

from alembic import op
from api.models.model_helpers import get_mediumblob  # type: ignore

# revision identifiers, used by Alembic.
revision = "3497d4c95cf9"
down_revision = "5cc5eea61ec4"
branch_labels = None
depends_on = None


def upgrade():
    existing_type = get_mediumblob(op.get_bind().dialect.name)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role_backend", "widgets", existing_type=existing_type, nullable=True)
    op.alter_column("role_backend", "templates", existing_type=existing_type, nullable=True)
    # ### end Alembic commands ###


def downgrade():
    existing_type = get_mediumblob(op.get_bind().dialect.name)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role_backend", "templates", existing_type=existing_type, nullable=False)
    op.alter_column("role_backend", "widgets", existing_type=existing_type, nullable=False)
    # ### end Alembic commands ###
