"""add group and user_group tables

Revision ID: 2d5abe125ef6
Revises: d64ba58254b9
Create Date: 2025-02-03 12:35:03.612708

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "2d5abe125ef6"
down_revision = "d64ba58254b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["entity_uuid"], ["entity.uuid"], name=op.f("fk_group_entity_uuid_entity")),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_group_entity_uuid"), "group", ["entity_uuid"], unique=False)
    op.create_table(
        "user_group",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("group_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["group_uuid"], ["group.uuid"], name=op.f("fk_user_group_group_uuid_group")),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("fk_user_group_user_uuid_user")),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_user_group_group_uuid"), "user_group", ["group_uuid"], unique=False)
    op.create_index(op.f("ix_user_group_user_uuid"), "user_group", ["user_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_group_user_uuid"), table_name="user_group")
    op.drop_index(op.f("ix_user_group_group_uuid"), table_name="user_group")
    op.drop_table("user_group")
    op.drop_index(op.f("ix_group_entity_uuid"), table_name="group")
    op.drop_table("group")
    # ### end Alembic commands ###
