"""add promps for roles

Revision ID: b7a5a4506af1
Revises: 942c93598bdb
Create Date: 2025-02-25 15:23:22.509973

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "b7a5a4506af1"
down_revision = "942c93598bdb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_prompt",
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("prompt_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("access", sa.String(length=100), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_uuid"],
            ["user_prompts.uuid"],
            name=op.f("fk_role_prompt_prompt_uuid_user_prompts"),
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["role.uuid"],
            name=op.f("fk_role_prompt_role_uuid_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_role_prompt_prompt_uuid"), "role_prompt", ["prompt_uuid"], unique=False)
    op.create_index(op.f("ix_role_prompt_role_uuid"), "role_prompt", ["role_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("uix_group_entity_name", "group", ["entity_uuid", "name"], unique=True)
    op.drop_index(op.f("ix_role_prompt_role_uuid"), table_name="role_prompt")
    op.drop_index(op.f("ix_role_prompt_prompt_uuid"), table_name="role_prompt")
    op.drop_table("role_prompt")
    # ### end Alembic commands ###
