"""decouple copilot_chats

Revision ID: bd05c027b86b
Revises: 50a057621532
Create Date: 2025-02-28 09:51:05.962601

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime, GzipJsonType

# revision identifiers, used by Alembic.
revision = "bd05c027b86b"
down_revision = "50a057621532"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "copilot_chat",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("content", GzipJsonType(), nullable=True),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("fk_copilot_chat_user_uuid_user")),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_copilot_chat_user_uuid"), "copilot_chat", ["user_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_copilot_chat_user_uuid"), table_name="copilot_chat")
    op.drop_table("copilot_chat")
    # ### end Alembic commands ###
