"""audit_entity_roles_permissions table

Revision ID: c63cd677f42c
Revises: a40c2e3ff322
Create Date: 2025-03-04 16:47:36.873370

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c63cd677f42c"
down_revision = "a40c2e3ff322"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_entity_roles_permissions",
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("performed_by_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("details", api.models.model_helpers.GzipJsonType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_audit_entity_roles_permissions_entity_uuid_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_uuid"],
            ["user.uuid"],
            name=op.f("fk_audit_entity_roles_permissions_performed_by_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["role.uuid"],
            name=op.f("fk_audit_entity_roles_permissions_role_uuid_role"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_audit_entity_roles_permissions_entity_uuid"),
        "audit_entity_roles_permissions",
        ["entity_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_entity_roles_permissions_performed_by_uuid"),
        "audit_entity_roles_permissions",
        ["performed_by_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_entity_roles_permissions_resource_uuid"),
        "audit_entity_roles_permissions",
        ["resource_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_entity_roles_permissions_role_uuid"),
        "audit_entity_roles_permissions",
        ["role_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_audit_entity_roles_permissions_role_uuid"),
        table_name="audit_entity_roles_permissions",
    )
    op.drop_index(
        op.f("ix_audit_entity_roles_permissions_resource_uuid"),
        table_name="audit_entity_roles_permissions",
    )
    op.drop_index(
        op.f("ix_audit_entity_roles_permissions_performed_by_uuid"),
        table_name="audit_entity_roles_permissions",
    )
    op.drop_index(
        op.f("ix_audit_entity_roles_permissions_entity_uuid"),
        table_name="audit_entity_roles_permissions",
    )
    op.drop_table("audit_entity_roles_permissions")
    # ### end Alembic commands ###
