"""on cascade deletion for resources used on roles

Revision ID: a40c2e3ff322
Revises: f883d456cae6
Create Date: 2025-03-03 12:03:45.093508

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "a40c2e3ff322"
down_revision = "f883d456cae6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_role_backend_backend_uuid_api_source", "role_backend", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_backend_backend_uuid_api_source"),
        "role_backend",
        "api_source",
        ["backend_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_role_file_file_uuid_file_widget", "role_file", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_file_file_uuid_file_widget"),
        "role_file",
        "file_widget",
        ["file_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_role_prompt_prompt_uuid_user_prompts", "role_prompt", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_prompt_prompt_uuid_user_prompts"),
        "role_prompt",
        "user_prompts",
        ["prompt_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_role_prompt_prompt_uuid_user_prompts"),
        "role_prompt",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_role_prompt_prompt_uuid_user_prompts",
        "role_prompt",
        "user_prompts",
        ["prompt_uuid"],
        ["uuid"],
    )
    op.drop_constraint(op.f("fk_role_file_file_uuid_file_widget"), "role_file", type_="foreignkey")
    op.create_foreign_key(
        "fk_role_file_file_uuid_file_widget",
        "role_file",
        "file_widget",
        ["file_uuid"],
        ["uuid"],
    )
    op.drop_constraint(
        op.f("fk_role_backend_backend_uuid_api_source"),
        "role_backend",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_role_backend_backend_uuid_api_source",
        "role_backend",
        "api_source",
        ["backend_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###
