"""add deleted_at column to audit_entity_roles_permissions

Revision ID: 73369b545913
Revises: c63cd677f42c
Create Date: 2025-03-06 15:12:17.484109

"""

import sqlalchemy as sa

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "73369b545913"
down_revision = "c63cd677f42c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column(
            "deleted_at",
            api.models.model_helpers.AwareDateTime(timezone=True),
            nullable=True,
        ),
    )
    dialect = op.get_bind().dialect.name
    if dialect == "mysql":
        op.drop_index("uix_role_entity_name", table_name="role")
    elif dialect == "postgresql":
        op.drop_constraint("uix_role_entity_name", "role", type_="unique")

    op.create_unique_constraint("uix_role_entity_name_deleted_at", "role", ["entity_uuid", "name", "deleted_at"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_role_entity_name_deleted_at", "role", type_="unique")
    op.create_index("uix_role_entity_name", "role", ["entity_uuid", "name"], unique=True)
    op.drop_column("role", "deleted_at")
    # ### end Alembic commands ###
