"""removes EntityPrompts

Revision ID: 2b976024e255
Revises: 11d741f183cb
Create Date: 2025-03-28 10:55:43.876439

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "2b976024e255"
down_revision = "11d741f183cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_entity_prompts_entity_uuid_entity", "entity_prompts", type_="foreignkey")
    op.drop_index("ix_entity_prompts_entity_uuid", table_name="entity_prompts")
    op.drop_table("entity_prompts")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_prompts",
        sa.Column("entity_uuid", sa.BINARY(length=16), nullable=False),
        sa.Column("prompt", sa.TEXT(), nullable=False),
        sa.Column("uuid", sa.BINARY(length=16), nullable=False),
        sa.Column("created_date", sa.DATETIME(), nullable=True),
        sa.Column("updated_date", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name="fk_entity_prompts_entity_uuid_entity",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_entity_prompts_entity_uuid", "entity_prompts", ["entity_uuid"], unique=False)
    # ### end Alembic commands ###
