"""add copilots column to holders

Revision ID: 4f6a1dc09a6b
Revises: 2b976024e255
Create Date: 2025-04-07 09:19:01.220985

"""

import sqlalchemy as sa

from alembic import op
from api.models.model_helpers import EncryptedType  # type: ignore

# revision identifiers, used by Alembic.
revision = "4f6a1dc09a6b"
down_revision = "2b976024e255"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_copilot",
        sa.Column("copilots", EncryptedType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_copilot", "copilots")
    # ### end Alembic commands ###
