"""add is_shared to dashboarditem

Revision ID: d40f7d35ba7f
Revises: 4f6a1dc09a6b
Create Date: 2025-06-06 12:53:05.707031

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "d40f7d35ba7f"
down_revision = "4f6a1dc09a6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dashboard_item", sa.Column("is_shared", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_dashboard_item_is_shared"),
        "dashboard_item",
        ["is_shared"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dashboard_item_is_shared"), table_name="dashboard_item")
    op.drop_column("dashboard_item", "is_shared")
    # ### end Alembic commands ###
