"""gzip long type

Revision ID: 5eecec288714
Revises: d40f7d35ba7f
Create Date: 2025-06-09 11:03:57.360582

"""

from alembic import op  # type: ignore
from api.models.model_helpers import GzipJsonLongType, get_mediumblob

# revision identifiers, used by Alembic.
revision = "5eecec288714"
down_revision = "d40f7d35ba7f"
branch_labels = None
depends_on = None


def upgrade():
    existing_type = get_mediumblob(op.get_bind().dialect.name)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "copilot_chat",
        "content",
        existing_type=existing_type,
        type_=GzipJsonLongType(),
        existing_nullable=True,
    )
    op.alter_column(
        "dashboard_item",
        "content",
        existing_type=existing_type,
        type_=GzipJsonLongType(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    type_ = get_mediumblob(op.get_bind().dialect.name)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dashboard_item",
        "content",
        existing_type=GzipJsonLongType(),
        type_=type_,
        existing_nullable=True,
    )
    op.alter_column(
        "copilot_chat",
        "content",
        existing_type=GzipJsonLongType(),
        type_=type_,
        existing_nullable=True,
    )
    # ### end Alembic commands ###
