"""add entity theme settings

Revision ID: e0cbd641e5b4
Revises: 5eecec288714
Create Date: 2025-07-02 16:43:46.534306

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models.model_helpers import AwareDateTime, GzipJsonType  # type: ignore

# revision identifiers, used by Alembic.
revision = "e0cbd641e5b4"
down_revision = "5eecec288714"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_theme_settings",
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("settings", GzipJsonType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_entity_theme_settings_entity_uuid_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_entity_theme_settings_entity_uuid"),
        "entity_theme_settings",
        ["entity_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entity_theme_settings_entity_uuid"), table_name="entity_theme_settings")
    op.drop_table("entity_theme_settings")
    # ### end Alembic commands ###
