"""widget_studio

Revision ID: ba0704e47566
Revises: e0cbd641e5b4
Create Date: 2025-07-24 09:54:15.285247

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import GzipJsonType

# revision identifiers, used by Alembic.
revision = "ba0704e47566"
down_revision = "e0cbd641e5b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "widget_metadata",
        sa.Column("widget_config", GzipJsonType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("widget_metadata", "widget_config")
    # ### end Alembic commands ###
