"""widget_type_check

Revision ID: 54884440a89b
Revises: ba0704e47566
Create Date: 2025-07-24 12:49:29.690371

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "54884440a89b"
down_revision = "ba0704e47566"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("widget_type_check", "widget_metadata", type_="check")
    op.create_check_constraint(
        "widget_type_check",
        "widget_metadata",
        "widget_type IN ('iframe', 'rss_viewer', 'rich_note', 'copilot_table', 'youtube', 'widget_studio')",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("widget_type_check", "widget_metadata", type_="check")
    op.create_check_constraint(
        "widget_type_check",
        "widget_metadata",
        "widget_type IN ('iframe', 'rss_viewer', 'rich_note', 'copilot_table', 'youtube')",
    )
    # ### end Alembic commands ###
