"""mcp_servers

Revision ID: 761bcf3af963
Revises: 54884440a89b
Create Date: 2025-08-21 10:24:07.389246

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models.model_helpers import AwareDateTime, GzipJsonType  # type: ignore

# revision identifiers, used by Alembic.
revision = "761bcf3af963"
down_revision = "54884440a89b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_servers",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("servers", GzipJsonType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("fk_mcp_servers_user_uuid_user")),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_mcp_servers_user_uuid"), "mcp_servers", ["user_uuid"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mcp_servers_user_uuid"), table_name="mcp_servers")
    op.drop_table("mcp_servers")
    # ### end Alembic commands ###
