"""user apps share

Revision ID: 34238bcde124
Revises: dcc0cffba914
Create Date: 2025-12-17 14:04:55.272020

"""

import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op
from api.models.model_helpers import AwareDateTime, JSONType  # type: ignore

# revision identifiers, used by Alembic.
revision = "34238bcde124"
down_revision = "dcc0cffba914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_app_share",
        sa.Column(
            "user_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "shared_user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "permissions",
            sa.Enum("view", "comment", "edit", name="permissionenum").with_variant(
                ENUM(
                    "view", "comment", "edit", name="permissionenum", create_type=False
                ),
                "postgresql",
            ),
            nullable=False,
        ),
        sa.Column("viewed", sa.Boolean(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shared_user_uuid"],
            ["user.uuid"],
            name=op.f("fk_user_app_share_shared_user_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["user_app_uuid"],
            ["user_app.uuid"],
            name=op.f("fk_user_app_share_user_app_uuid_user_app"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_user_app_share_active"), "user_app_share", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_user_app_share_shared_user_uuid"),
        "user_app_share",
        ["shared_user_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_app_share_user_app_uuid"),
        "user_app_share",
        ["user_app_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_app_share_viewed"), "user_app_share", ["viewed"], unique=False
    )
    op.add_column(
        "permissions_invite",
        sa.Column("shared_apps", JSONType(), nullable=True),
    )
    op.add_column("user_app", sa.Column("is_shared", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_user_app_is_shared"), "user_app", ["is_shared"], unique=False
    )
    op.create_index(
        op.f("ix_user_app_user_uuid"), "user_app", ["user_uuid"], unique=False
    )
    op.add_column(
        "user_pro_invite",
        sa.Column("shared_apps", JSONType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_pro_invite", "shared_apps")
    op.drop_index(op.f("ix_user_app_user_uuid"), table_name="user_app")
    op.drop_index(op.f("ix_user_app_is_shared"), table_name="user_app")
    op.drop_column("user_app", "is_shared")
    op.drop_column("permissions_invite", "shared_apps")
    op.drop_index(op.f("ix_user_app_share_viewed"), table_name="user_app_share")
    op.drop_index(op.f("ix_user_app_share_user_app_uuid"), table_name="user_app_share")
    op.drop_index(
        op.f("ix_user_app_share_shared_user_uuid"), table_name="user_app_share"
    )
    op.drop_index(op.f("ix_user_app_share_active"), table_name="user_app_share")
    op.drop_table("user_app_share")
    # ### end Alembic commands ###
