"""user apps data

Revision ID: dcc0cffba914
Revises: c8f0b4ddbe33
Create Date: 2025-12-11 10:03:46.346949

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models.model_helpers import AwareDateTime, GzipJsonLongType  # type: ignore

# revision identifiers, used by Alembic.
revision = "dcc0cffba914"
down_revision = "c8f0b4ddbe33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_app",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("content", GzipJsonLongType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_user_app_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_app")
    # ### end Alembic commands ###
