"""user apps shared files

Revision ID: 1f15b1c36b45
Revises: aa8e4209c033
Create Date: 2026-01-08 10:23:09.952664

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "1f15b1c36b45"
down_revision = "aa8e4209c033"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stored_file_share",
        sa.Column(
            "user_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
    )
    op.alter_column(
        "stored_file_share",
        "dashboard_item_uuid",
        existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_stored_file_share_user_app_uuid"),
        "stored_file_share",
        ["user_app_uuid"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_stored_file_share_user_app_uuid_user_app"),
        "stored_file_share",
        "user_app",
        ["user_app_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_stored_file_share_user_app_uuid_user_app"),
        "stored_file_share",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_stored_file_share_user_app_uuid"), table_name="stored_file_share"
    )
    op.alter_column(
        "stored_file_share",
        "dashboard_item_uuid",
        existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
        nullable=False,
    )
    op.drop_column("stored_file_share", "user_app_uuid")
    # ### end Alembic commands ###
