"""delete entity

Revision ID: d915cb8992fa
Revises: dcc0cffba914
Create Date: 2025-12-31 11:58:45.807394

"""

from contextlib import suppress

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "d915cb8992fa"
down_revision = "dcc0cffba914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_audit_entity_roles_permissions_entity_uuid_entity"),
        "audit_entity_roles_permissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_audit_entity_roles_permissions_entity_uuid_entity"),
        "audit_entity_roles_permissions",
        "entity",
        ["entity_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    for const in [
        "entity_entitlement_ibfk_1",
        "fk_entity_entitlement_entity_uuid_entity",
    ]:
        with suppress(Exception):
            op.drop_constraint(
                op.f(const), "entity_entitlement", type_="foreignkey", if_exists=True
            )

    op.create_foreign_key(
        op.f("fk_entity_entitlement_entity_uuid_entity"),
        "entity_entitlement",
        "entity",
        ["entity_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )

    for const in [
        "permissions_entity_map_ibfk_1",
        "fk_permissions_entity_map_entity_uuid_entity",
    ]:
        with suppress(Exception):
            op.drop_constraint(
                op.f(const),
                "permissions_entity_map",
                type_="foreignkey",
                if_exists=True,
            )

    op.create_foreign_key(
        op.f("fk_permissions_entity_map_entity_uuid_entity"),
        "permissions_entity_map",
        "entity",
        ["entity_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )

    for const in [
        "permissions_invite_ibfk_1",
        "fk_permissions_invite_permissions_uuid_permissions_entity_map",
    ]:
        with suppress(Exception):
            op.drop_constraint(
                op.f(const), "permissions_invite", type_="foreignkey", if_exists=True
            )

    op.create_foreign_key(
        op.f("fk_permissions_invite_permissions_uuid_permissions_entity_map"),
        "permissions_invite",
        "permissions_entity_map",
        ["permissions_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_role_entity_uuid_entity"), "role", type_="foreignkey", if_exists=True
    )
    op.create_foreign_key(
        op.f("fk_role_entity_uuid_entity"),
        "role",
        "entity",
        ["entity_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_user_permissions_uuid"), "user", ["permissions_uuid"], unique=False
    )

    for const in [
        "user_pro_invite_ibfk_2",
        "fk_user_pro_invite_permissions_uuid_permissions_entity_map",
    ]:
        with suppress(Exception):
            op.drop_constraint(
                op.f(const), "user_pro_invite", type_="foreignkey", if_exists=True
            )

    op.create_foreign_key(
        op.f("fk_user_pro_invite_permissions_uuid_permissions_entity_map"),
        "user_pro_invite",
        "permissions_entity_map",
        ["permissions_uuid"],
        ["uuid"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_pro_invite_permissions_uuid_permissions_entity_map"),
        "user_pro_invite",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_pro_invite_permissions_uuid_permissions_entity_map"),
        "user_pro_invite",
        "permissions_entity_map",
        ["permissions_uuid"],
        ["uuid"],
    )
    op.drop_index(op.f("ix_user_permissions_uuid"), table_name="user")
    op.drop_constraint(op.f("fk_role_entity_uuid_entity"), "role", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_role_entity_uuid_entity"), "role", "entity", ["entity_uuid"], ["uuid"]
    )
    op.drop_constraint(
        op.f("fk_permissions_invite_permissions_uuid_permissions_entity_map"),
        "permissions_invite",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_permissions_invite_permissions_uuid_permissions_entity_map"),
        "permissions_invite",
        "permissions_entity_map",
        ["permissions_uuid"],
        ["uuid"],
    )
    op.drop_constraint(
        op.f("fk_permissions_entity_map_entity_uuid_entity"),
        "permissions_entity_map",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("permissions_entity_map_ibfk_1"),
        "permissions_entity_map",
        "entity",
        ["entity_uuid"],
        ["uuid"],
    )
    op.drop_constraint(
        op.f("fk_entity_entitlement_entity_uuid_entity"),
        "entity_entitlement",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_entity_entitlement_entity_uuid_entity"),
        "entity_entitlement",
        "entity",
        ["entity_uuid"],
        ["uuid"],
    )
    op.drop_constraint(
        op.f("fk_audit_entity_roles_permissions_entity_uuid_entity"),
        "audit_entity_roles_permissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_audit_entity_roles_permissions_entity_uuid_entity"),
        "audit_entity_roles_permissions",
        "entity",
        ["entity_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###
