"""entity backends

Revision ID: 417d5d1e9ed8
Revises: 1f15b1c36b45
Create Date: 2026-02-06 09:49:29.385538

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "417d5d1e9ed8"
down_revision = "1f15b1c36b45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_source",
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    )
    op.alter_column(
        "api_source",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "api_source",
        "user_uuid",
        existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_api_source_entity_uuid"), "api_source", ["entity_uuid"], unique=False
    )
    op.create_index(
        "ix_user_entity_name_api_source",
        "api_source",
        ["user_uuid", "entity_uuid", "name"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_api_source_entity_uuid_entity"),
        "api_source",
        "entity",
        ["entity_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.add_column(
        "data_bundle", sa.Column("allow_custom_backends", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "entitlement", sa.Column("allow_custom_backends", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "entity_entitlement",
        sa.Column("allow_custom_backends", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity_entitlement", "allow_custom_backends")
    op.drop_column("entitlement", "allow_custom_backends")
    op.drop_column("data_bundle", "allow_custom_backends")
    op.drop_constraint(
        op.f("fk_api_source_entity_uuid_entity"), "api_source", type_="foreignkey"
    )
    op.drop_index("ix_user_entity_name_api_source", table_name="api_source")
    op.drop_index(op.f("ix_api_source_entity_uuid"), table_name="api_source")
    op.alter_column(
        "api_source",
        "user_uuid",
        existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
        nullable=False,
    )
    op.alter_column(
        "api_source",
        "name",
        existing_type=sa.String(length=200),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("api_source", "entity_uuid")
    # ### end Alembic commands ###
