"""add chart and html widget types

Revision ID: 7bc3e1e8f4ac
Revises: dcc0cffba914
Create Date: 2026-02-08

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "7bc3e1e8f4ac"
down_revision = "dcc0cffba914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("widget_type_check", "widget_metadata", type_="check")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "widget_type_check",
        "widget_metadata",
        "widget_type IN ('iframe', 'rss_viewer', 'rich_note', 'copilot_table', 'youtube', 'widget_studio')",
    )
    # ### end Alembic commands ###
