"""add user skills table

Revision ID: e1db813b9c35
Revises: 7b5d850c335f
Create Date: 2026-02-19 13:48:01.121686

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models import model_helpers

# revision identifiers, used by Alembic.
revision = "e1db813b9c35"
down_revision = "7b5d850c335f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_skills",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", model_helpers.GzipStringType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_user_skills_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "slug", name="uq_user_skills_user_uuid_slug"),
    )
    op.create_index(
        op.f("ix_user_skills_user_uuid"), "user_skills", ["user_uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_skills_user_uuid"), table_name="user_skills")
    op.drop_table("user_skills")
    # ### end Alembic commands ###
