"""add marketplace tables

Revision ID: 78cfa7d6b4a6
Revises: e1db813b9c35
Create Date: 2026-03-19 09:16:54.328947

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models import model_helpers  # type: ignore

# revision identifiers, used by Alembic.
revision = "78cfa7d6b4a6"
down_revision = "e1db813b9c35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=512), nullable=True),
        sa.Column("documentation_url", sa.String(length=512), nullable=True),
        sa.Column("support_email", sa.String(length=255), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "vendor_app",
        sa.Column(
            "vendor_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
        sa.Column("screenshots", model_helpers.JSONType(), nullable=True),
        sa.Column("api_key_url", sa.String(length=512), nullable=True),
        sa.Column("more_information_url", sa.String(length=512), nullable=True),
        sa.Column("backend_base_url", sa.String(length=512), nullable=True),
        sa.Column("apps_json_url", sa.String(length=512), nullable=True),
        sa.Column("widgets_json_url", sa.String(length=512), nullable=True),
        sa.Column("is_built_in", sa.Boolean(), nullable=False),
        sa.Column("auth_type", model_helpers.JSONType(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "verified",
                "published",
                "disabled",
                "removed",
                name="appstatus",
            ),
            nullable=False,
        ),
        sa.Column("apps_json_cache", model_helpers.GzipJsonType(), nullable=True),
        sa.Column("widgets_json_cache", model_helpers.GzipJsonType(), nullable=True),
        sa.Column("apps_json_version", sa.String(length=100), nullable=True),
        sa.Column("widgets_json_version", sa.String(length=100), nullable=True),
        sa.Column("last_fetched_at", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("last_fetch_status", sa.String(length=10), nullable=True),
        sa.Column("last_fetch_error", sa.Text(), nullable=True),
        sa.Column("last_verified_at", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["vendor_uuid"],
            ["vendor.uuid"],
            name=op.f("fk_vendor_app_vendor_uuid_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_vendor_app_status"), "vendor_app", ["status"], unique=False
    )
    op.create_index(
        "ix_vendor_app_vendor_status",
        "vendor_app",
        ["vendor_uuid", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_app_vendor_uuid"), "vendor_app", ["vendor_uuid"], unique=False
    )
    op.create_table(
        "user_app_subscription",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disconnected", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column("subscribed_at", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("disconnected_at", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_uuid"],
            ["vendor_app.uuid"],
            name=op.f("fk_user_app_subscription_app_uuid_vendor_app"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_user_app_subscription_user_uuid_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "app_uuid", name="uq_user_app_subscription"),
    )
    op.create_index(
        "ix_user_app_sub_user_status",
        "user_app_subscription",
        ["user_uuid", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_app_subscription_app_uuid"),
        "user_app_subscription",
        ["app_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_app_subscription_user_uuid"),
        "user_app_subscription",
        ["user_uuid"],
        unique=False,
    )

    op.create_table(
        "rate_vendor_app",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_uuid"],
            ["vendor_app.uuid"],
            name=op.f("fk_rate_vendor_app_app_uuid_vendor_app"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_rate_vendor_app_user_uuid_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "app_uuid", name="uq_user_app_rating"),
    )
    op.create_index(
        op.f("ix_rate_vendor_app_app_uuid"),
        "rate_vendor_app",
        ["app_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_vendor_app_user_uuid"),
        "rate_vendor_app",
        ["user_uuid"],
        unique=False,
    )

    op.add_column(
        "api_source",
        sa.Column(
            "vendor_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_api_source_vendor_app_uuid"),
        "api_source",
        ["vendor_app_uuid"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_api_source_vendor_app_uuid_vendor_app"),
        "api_source",
        "vendor_app",
        ["vendor_app_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rate_vendor_app_user_uuid"), table_name="rate_vendor_app")
    op.drop_index(op.f("ix_rate_vendor_app_app_uuid"), table_name="rate_vendor_app")
    op.drop_table("rate_vendor_app")
    op.drop_constraint(
        op.f("fk_api_source_vendor_app_uuid_vendor_app"),
        "api_source",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_api_source_vendor_app_uuid"), table_name="api_source")
    op.drop_column("api_source", "vendor_app_uuid")
    op.drop_table("user_app_subscription")
    op.drop_table("vendor_app")
    op.drop_table("vendor")
    # ### end Alembic commands ###
