"""remove bot

Revision ID: a82c1f4d7e9b
Revises: b79397e6db4a
Create Date: 2026-05-15 11:59:50.203838

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models import model_helpers  # type: ignore

# revision identifiers, used by Alembic.
revision = "a82c1f4d7e9b"
down_revision = "b79397e6db4a"
branch_labels = None
depends_on = None


USER_COLUMNS_TO_DROP = [
    "feedback_like",
    "linkedin",
    "investing_for_client",
    "hubspot_id",
    "alerts_count",
    "features_terminal_style",
    "features_settings",
    "features_keys",
    "feedback_to_pay",
    "club_name",
    "role",
    "hours_per_week",
    "society_name",
    "feedback_improve",
    "github",
    "telegram",
    "investment_approach",
    "data_connector_url",
    "organization_type",
    "campaign_source",
    "fund_name",
    "country",
    "organization_country",
    "university",
    "features",
    "features_sources",
    "locale",
    "promo_code",
    "discord",
    "organization_size",
    "features_pro_info",
    "twitter",
    "other_student_field",
    "job_role",
    "bio",
    "explain_investment_club",
    "chargebee_user_id",
    "source",
    "features_server",
]

# This order avoids foreign key constraint issues when dropping tables.
TABLES_TO_DROP = [
    "trans_plan",
    "sub_plan",
    "charge_plan",
    "plan",
    "transaction",
    "webhook",
    "platform",
    "subscription",
    "feature",
    "tauribuild",
    "info_store",
    "script_upvote",
    "demo",
    "pro_download",
    "tauri_log",
    "change",
    "script",
    "reconciliation",
    "chargebee",
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in TABLES_TO_DROP:
        op.drop_table(table_name)

    # Drop user columns
    for column_name in USER_COLUMNS_TO_DROP:
        op.drop_column("user", column_name)

    # ### end Alembic commands ###


def downgrade():  # noqa: PLR0915
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("feedback_like", sa.TEXT(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "investing_for_client",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("user", sa.Column("job_role", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("features_settings", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("role", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("fund_name", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("organization_country", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("discord", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("features_keys", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("data_connector_url", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("explain_investment_club", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("source", sa.VARCHAR(length=100), nullable=True))
    op.add_column("user", sa.Column("linkedin", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("features_server", model_helpers.JSONType(), nullable=True))
    op.add_column("user", sa.Column("github", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("campaign_source", sa.VARCHAR(length=100), nullable=True))
    op.add_column(
        "user",
        sa.Column("hubspot_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column("user", sa.Column("investment_approach", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("club_name", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("society_name", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("hours_per_week", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("features", model_helpers.JSONType(), nullable=True))
    op.add_column(
        "user",
        sa.Column("alerts_count", sa.Integer(), autoincrement=False, nullable=False),
    )
    op.add_column("user", sa.Column("features_sources", model_helpers.JSONType(), nullable=True))
    op.add_column("user", sa.Column("organization_size", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("bio", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("features_pro_info", model_helpers.JSONType(), nullable=True))
    op.add_column("user", sa.Column("feedback_to_pay", sa.TEXT(), nullable=True))
    op.add_column(
        "user",
        sa.Column("features_terminal_style", model_helpers.JSONType(), nullable=True),
    )
    op.add_column("user", sa.Column("promo_code", sa.VARCHAR(length=100), nullable=True))
    op.add_column("user", sa.Column("university", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("chargebee_user_id", sa.VARCHAR(length=50), nullable=True))
    op.add_column("user", sa.Column("telegram", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("feedback_improve", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("organization_type", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("locale", sa.VARCHAR(length=100), nullable=True))
    op.add_column("user", sa.Column("twitter", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("country", sa.VARCHAR(length=100), nullable=True))
    op.add_column("user", sa.Column("other_student_field", sa.TEXT(), nullable=True))

    op.create_table(
        "subscription",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("chargebee_subscription_id", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("paid_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("next_bill_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("cancel_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("cancel_reason", sa.VARCHAR(length=1000), nullable=True),
        sa.Column(
            "is_group",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(length=15), nullable=False),
        sa.Column("coupons", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("subscription_ibfk_1")),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("chargebee_subscription_id"),
        "subscription",
        ["chargebee_subscription_id"],
        unique=True,
    )
    op.create_table(
        "transaction",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("subscription_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("start_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("end_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("cancel_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_uuid"],
            ["subscription.uuid"],
            name=op.f("transaction_ibfk_1"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "plan",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("chargebee_plan_id", sa.VARCHAR(length=50), nullable=True),
        sa.Column("external_name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("features", model_helpers.JSONType(), nullable=True),
        sa.Column("description", sa.VARCHAR(length=1000), nullable=True),
        sa.Column(
            "popular",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("item_type", sa.VARCHAR(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("currency_code", sa.VARCHAR(length=5), nullable=True),
        sa.Column("period_unit", sa.VARCHAR(length=10), nullable=True),
        sa.Column("start_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("end_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("quantity", sa.FLOAT(), nullable=True),
        sa.Column("unit_price", sa.FLOAT(), nullable=True),
        sa.Column("amount", sa.FLOAT(), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "trans_plan",
        sa.Column("transaction_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("plan_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(["plan_uuid"], ["plan.uuid"], name=op.f("trans_plan_ibfk_1")),
        sa.ForeignKeyConstraint(["transaction_uuid"], ["transaction.uuid"], name=op.f("trans_plan_ibfk_2")),
        sa.PrimaryKeyConstraint("transaction_uuid", "plan_uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "chargebee",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("event_type", sa.VARCHAR(length=100), nullable=True),
        sa.Column("customer_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("customer_email", sa.VARCHAR(length=100), nullable=True),
        sa.Column("payment_type", sa.VARCHAR(length=100), nullable=True),
        sa.Column("payment_reference_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("payment_gateway", sa.VARCHAR(length=100), nullable=True),
        sa.Column("invoice_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("invoice_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("invoice_due_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("invoice_amount_paid", sa.VARCHAR(length=100), nullable=True),
        sa.Column("invoice_total", sa.VARCHAR(length=100), nullable=True),
        sa.Column("invoice_paid_at", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("subscription_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("subscription_billing_period", sa.VARCHAR(length=100), nullable=True),
        sa.Column("subscription_billing_period_unit", sa.VARCHAR(length=100), nullable=True),
        sa.Column("transaction_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("transaction_gateway", sa.VARCHAR(length=100), nullable=True),
        sa.Column("transaction_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("transaction_payment_method", sa.VARCHAR(length=100), nullable=True),
        sa.Column("transaction_amount", sa.VARCHAR(length=100), nullable=True),
        sa.Column("transaction_linked_invoices", sa.VARCHAR(length=1000), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "feature",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("feature_id", sa.VARCHAR(length=100), nullable=False),
        sa.Column("votes", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("emails", sa.TEXT(), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("feature_id"), "feature", ["feature_id"], unique=True)
    op.create_table(
        "script",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("user_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("script", sa.TEXT(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("version", sa.VARCHAR(length=20), nullable=False),
        sa.Column(
            "public",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("tags", sa.TEXT(), nullable=True),
        sa.Column("slug", sa.VARCHAR(length=200), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.uuid"], name=op.f("script_ibfk_1")),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("slug_user_id_unique"), "script", ["slug", "user_id"], unique=True)
    op.create_index(op.f("name_user_id_unique"), "script", ["name", "user_id"], unique=True)
    op.create_table(
        "platform",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("subscription_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("platform_id", sa.VARCHAR(length=129), nullable=False),
        sa.Column(
            "is_group",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("monthly_freecommand", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("monthly_reset_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("daily_freecommand", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("daily_reset_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column(
            "active",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["subscription_uuid"], ["subscription.uuid"], name=op.f("platform_ibfk_1")),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "script_upvote",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("script_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["script_uuid"], ["script.uuid"], name=op.f("script_upvote_ibfk_1")),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("script_upvote_ibfk_2")),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "webhook",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("platform_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("url", sa.TEXT(), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["platform_uuid"], ["platform.uuid"], name=op.f("webhook_ibfk_1")),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "info_store",
        sa.Column("key", sa.VARCHAR(length=100), nullable=False),
        sa.Column("value", sa.TEXT(), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "tauribuild",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("url", sa.TEXT(), nullable=False),
        sa.Column("version", sa.VARCHAR(length=12), nullable=False),
        sa.Column("system", sa.VARCHAR(length=100), nullable=False),
        sa.Column("notes", sa.TEXT(), nullable=False),
        sa.Column("pub_date", model_helpers.AwareDateTime(), nullable=False),
        sa.Column("signature", sa.TEXT(), nullable=False),
        sa.Column("item_type", sa.VARCHAR(length=100), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("tauri_type", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "change",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("table_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("change_type", sa.VARCHAR(length=100), nullable=True),
        sa.Column("target_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("target_column", sa.VARCHAR(length=100), nullable=True),
        sa.Column("before", sa.VARCHAR(length=1000), nullable=True),
        sa.Column("after", sa.VARCHAR(length=1000), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "pro_download",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("version", sa.TEXT(), nullable=True),
        sa.Column("system", sa.TEXT(), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], name=op.f("pro_download_ibfk_1")),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_pro_download_user_uuid"), "pro_download", ["user_uuid"], unique=False)
    op.create_table(
        "demo",
        sa.Column(
            "used_before",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("first_name", sa.TEXT(), nullable=False),
        sa.Column("last_name", sa.TEXT(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "reconciliation",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("chargebee_subscription_id", sa.VARCHAR(length=50), nullable=True),
        sa.Column("status", sa.VARCHAR(length=15), nullable=False),
        sa.Column("next_bill_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("user_uuid", sa.VARCHAR(length=50), nullable=True),
        sa.Column("plans", sa.VARCHAR(length=1000), nullable=True),
        sa.Column("source", sa.VARCHAR(length=15), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "sub_plan",
        sa.Column("subscription_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("plan_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(["plan_uuid"], ["plan.uuid"], name=op.f("sub_plan_ibfk_1")),
        sa.ForeignKeyConstraint(["subscription_uuid"], ["subscription.uuid"], name=op.f("sub_plan_ibfk_2")),
        sa.PrimaryKeyConstraint("subscription_uuid", "plan_uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "charge_plan",
        sa.Column("chargebee_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("plan_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(["chargebee_uuid"], ["chargebee.uuid"], name=op.f("charge_plan_ibfk_1")),
        sa.ForeignKeyConstraint(["plan_uuid"], ["plan.uuid"], name=op.f("charge_plan_ibfk_2")),
        sa.PrimaryKeyConstraint("chargebee_uuid", "plan_uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "tauri_log",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("log_type", sa.VARCHAR(length=200), nullable=False),
        sa.Column("identifier", sa.VARCHAR(length=200), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("identifier_date_unique"),
        "tauri_log",
        ["identifier", "date", "log_type"],
        unique=True,
    )

    # ### end Alembic commands ###
