"""vendor app columns

Revision ID: aa2dbc69abd0
Revises: b7c2a3e5d9f1
Create Date: 2026-04-20 10:59:20.414520

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa2dbc69abd0"
down_revision = "b7c2a3e5d9f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vendor", sa.Column("thumbnail_url", sa.Text(), nullable=True))
    op.add_column(
        "vendor_app",
        sa.Column("api_key_info_url", sa.String(length=512), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendor_app", "api_key_info_url")
    op.drop_column("vendor", "thumbnail_url")
    # ### end Alembic commands ###
