"""vendor app parent uuid

Revision ID: d7032d8f9c87
Revises: aa2dbc69abd0
Create Date: 2026-04-20 14:56:25.589852

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.base import AppStatus
from api.models.marketplace_models import VendorApp  # type: ignore

# revision identifiers, used by Alembic.
revision = "d7032d8f9c87"
down_revision = "aa2dbc69abd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendor_app",
        sa.Column(
            "parent_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_vendor_app_parent_app_uuid"),
        "vendor_app",
        ["parent_app_uuid"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_vendor_app_parent_app_uuid_vendor_app"),
        "vendor_app",
        "vendor_app",
        ["parent_app_uuid"],
        ["uuid"],
        ondelete="SET NULL",
    )

    # Backfill parent_app_uuid for existing apps based on vendor + name,
    # pointing to the latest published version as the parent
    conn = op.get_bind()

    parent_app_subquery = (
        sa.select(
            VendorApp.vendor_uuid,
            VendorApp.uuid.label("app_uuid"),
            VendorApp.name,
            VendorApp.version,
        )
        .where(VendorApp.status == AppStatus.published)
        .order_by(VendorApp.vendor_uuid, VendorApp.name, VendorApp.version.desc())
        .distinct(VendorApp.vendor_uuid, VendorApp.name)
        .subquery()
    )

    query = sa.select(
        VendorApp.uuid, parent_app_subquery.c.app_uuid.label("parent_app_uuid")
    ).join(
        parent_app_subquery,
        (VendorApp.vendor_uuid == parent_app_subquery.c.vendor_uuid)
        & (VendorApp.name == parent_app_subquery.c.name)
        & (VendorApp.uuid != parent_app_subquery.c.app_uuid),
    )

    results = conn.execute(query).fetchall()

    if not results:
        return

    for app_uuid, parent_app_uuid in results:
        if parent_app_uuid is not None:
            conn.execute(
                sa.update(VendorApp)
                .where(VendorApp.uuid == app_uuid)
                .values(parent_app_uuid=parent_app_uuid)
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_vendor_app_parent_app_uuid_vendor_app"),
        "vendor_app",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_vendor_app_parent_app_uuid"), table_name="vendor_app")
    op.drop_column("vendor_app", "parent_app_uuid")
    # ### end Alembic commands ###
