"""vendor app fields

Revision ID: b79397e6db4a
Revises: 4b1f9c8a2d35
Create Date: 2026-05-04 10:30:36.167629

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "b79397e6db4a"
down_revision = "4b1f9c8a2d35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendor_app", sa.Column("category", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "vendor_app", sa.Column("tagline", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendor_app", "tagline")
    op.drop_column("vendor_app", "category")
    # ### end Alembic commands ###
