"""add stripe_id to user

Adds a nullable, indexed stripe_id column to the user table so the Lite
Checkout webhook can look up a user by Stripe customer ID on renewal and
cancellation events.

Revision ID: 7f2e1b4314ef
Revises: a82c1f4d7e9b
Create Date: 2026-06-29 13:55:36.038483

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "7f2e1b4314ef"
down_revision = "a82c1f4d7e9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("stripe_id", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_user_stripe_id"), "user", ["stripe_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_stripe_id"), table_name="user")
    op.drop_column("user", "stripe_id")
    # ### end Alembic commands ###
