"""redid script upvoting

Revision ID: 192e2c9ee8cf
Revises: 20799d0bdfea
Create Date: 2023-02-08 14:53:26.007268

"""

import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "192e2c9ee8cf"
down_revision = "20799d0bdfea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "script_upvote",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("script_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["script_uuid"],
            ["script.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.drop_column("script", "upvotes")
    op.drop_column("script", "downvotes")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "script",
        sa.Column(
            "downvotes",
            sa.INTEGER().with_variant(mysql.INTEGER(display_width=11), "mysql"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "script",
        sa.Column(
            "upvotes",
            sa.INTEGER().with_variant(mysql.INTEGER(display_width=11), "mysql"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("script_upvote")
    # ### end Alembic commands ###
