"""add fk on entitlements to data bundle

Revision ID: 196a22e4d443
Revises: 6739c286b167
Create Date: 2024-08-19 10:42:10.827606

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "196a22e4d443"
down_revision = "6739c286b167"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entitlement",
        sa.Column("data_bundle_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    )
    op.create_foreign_key(None, "entitlement", "data_bundle", ["data_bundle_uuid"], ["uuid"])
    op.drop_column("entitlement", "data_bundle")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entitlement",
        sa.Column(
            "data_bundle",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "entitlement", type_="foreignkey")
    op.drop_column("entitlement", "data_bundle_uuid")
    # ### end Alembic commands ###
