"""Create a totp active boolean

Revision ID: 1b27503b4057
Revises: 9988e8e8d51f
Create Date: 2024-03-13 09:25:13.276221

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "1b27503b4057"
down_revision = "9988e8e8d51f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("totp_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "totp_active")
    # ### end Alembic commands ###
