"""Add data connector url

Revision ID: 1b9afb4d6f15
Revises: a780982dbd27
Create Date: 2024-01-29 10:35:13.180609

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "1b9afb4d6f15"
down_revision = "a780982dbd27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("data_connector_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "data_connector_url")
    # ### end Alembic commands ###
