"""Removed json token

Revision ID: 1cd1cba690dd
Revises: 7ec763e44c69
Create Date: 2023-01-27 08:27:49.413816

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "1cd1cba690dd"
down_revision = "7ec763e44c69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "json_token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("json_token", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
