"""create usage table

Revision ID: 1d192ffa1f0c
Revises: 196a22e4d443
Create Date: 2024-08-19 16:59:31.798884

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "1d192ffa1f0c"
down_revision = "196a22e4d443"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entitlement_usage",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("number_copilot_calls_day_count", sa.Integer(), nullable=False),
        sa.Column("total_file_upload_size_gb_count", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_entitlement_usage_user_uuid"),
        "entitlement_usage",
        ["user_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entitlement_usage_user_uuid"), table_name="entitlement_usage")
    op.drop_table("entitlement_usage")
    # ### end Alembic commands ###
