"""remove trial columns

Revision ID: 1d38578762fa
Revises: 66642a0d22e9
Create Date: 2024-08-09 10:08:03.076505

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "1d38578762fa"
down_revision = "66642a0d22e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entitlement", "is_trial")
    op.drop_column("entitlement", "trial_expiration_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entitlement", sa.Column("trial_expiration_date", sa.DATETIME(), nullable=True))
    op.add_column(
        "entitlement",
        sa.Column(
            "is_trial",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
