"""Adds columns for terminal

Revision ID: 1eaaedd86b49
Revises: ccfdf08df4d1
Create Date: 2022-10-28 08:35:21.485084

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "1eaaedd86b49"
down_revision = "ccfdf08df4d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login", sa.Column("is_terminal", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("features_settings", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("features_keys", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "features_keys")
    op.drop_column("user", "features_settings")
    op.drop_column("login", "is_terminal")
    # ### end Alembic commands ###
