"""Added script unique constraint and description

Revision ID: 20799d0bdfea
Revises: 1cd1cba690dd
Create Date: 2023-02-01 11:18:51.926952

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "20799d0bdfea"
down_revision = "1cd1cba690dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("script", sa.Column("description", sa.Text(), nullable=True))
    op.create_unique_constraint("name_user_id_unique", "script", ["name", "user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_user_id_unique", "script", type_="unique")
    op.drop_column("script", "description")
    # ### end Alembic commands ###
