"""Dont force invite emails to be unqiue

Revision ID: 20f8ab217c97
Revises: 8dbbec2fc303
Create Date: 2024-04-17 13:57:13.664920

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "20f8ab217c97"
down_revision = "8dbbec2fc303"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    if dialect == "mysql":
        op.drop_index("user_pro_unqiue_email", table_name="user_pro_invite")
    elif dialect == "postgresql":
        op.drop_constraint("user_pro_unqiue_email", "user_pro_invite", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("user_pro_unqiue_email", "user_pro_invite", ["email"], unique=True)
    # ### end Alembic commands ###
