"""add coupons to sub

Revision ID: 215847288e23
Revises: d1a34ad9276d
Create Date: 2022-09-28 07:49:20.739486

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "215847288e23"
down_revision = "d1a34ad9276d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("coupons", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "coupons")
    # ### end Alembic commands ###
