"""Changing copilot_chat table to have only 2 columns: user_uuid(fk) and chats

Revision ID: 2210e6a21ee2
Revises: 00dddde76cd0
Create Date: 2024-07-09 17:28:05.215721

"""

import sqlalchemy as sa

from alembic import op
from api.models.model_helpers import GzipJsonType, get_mediumblob  # type: ignore

# revision identifiers, used by Alembic.
revision = "2210e6a21ee2"
down_revision = "00dddde76cd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "copilot_chat",
        sa.Column("chats", GzipJsonType(), nullable=True),
    )
    op.drop_column("copilot_chat", "messages")
    op.drop_column("copilot_chat", "name")
    # ### end Alembic commands ###


def downgrade():
    dialect = op.get_bind().dialect.name
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copilot_chat", sa.Column("name", sa.TEXT(), nullable=False))
    op.add_column("copilot_chat", sa.Column("messages", get_mediumblob(dialect), nullable=True))
    op.drop_column("copilot_chat", "chats")
    # ### end Alembic commands ###
