"""Add jose fields to single widgets

Revision ID: 25add7f11619
Revises: 0c8b83c6f1eb
Create Date: 2024-04-23 16:09:07.956753

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "25add7f11619"
down_revision = "0c8b83c6f1eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "single_widget", sa.Column("source", sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True)
    )
    op.add_column("single_widget", sa.Column("category", sa.Text(), nullable=True))
    op.add_column("single_widget", sa.Column("sub_category", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("single_widget", "sub_category")
    op.drop_column("single_widget", "category")
    op.drop_column("single_widget", "source")
    # ### end Alembic commands ###
