"""Make wants contacted optional

Revision ID: 28acf3c420b7
Revises: 4080feb59e06
Create Date: 2023-11-06 14:52:53.154747

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "28acf3c420b7"
down_revision = "4080feb59e06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "wants_contacted",
        existing_type=sa.Boolean(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "wants_contacted",
        existing_type=sa.Boolean(),
        nullable=False,
    )
    # ### end Alembic commands ###
