"""supreme_entity_relationship

Revision ID: 2b450b3a50b8
Revises: e89d0a626693
Create Date: 2023-06-30 16:44:17.092166

"""

import sqlalchemy as sa
from sqlalchemy_utils.types.uuid import UUIDType

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "2b450b3a50b8"
down_revision = "e89d0a626693"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity_relationship", sa.Column("supreme_uuid", UUIDType(), nullable=False))
    op.create_foreign_key(None, "entity_relationship", "entity", ["supreme_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "entity_relationship", type_="foreignkey")
    op.drop_column("entity_relationship", "supreme_uuid")
    # ### end Alembic commands ###
