"""Refactor pro models

Revision ID: 321b4ae75bdf
Revises: 28acf3c420b7
Create Date: 2023-11-09 12:14:17.589267

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import ProEntitlementsType

# revision identifiers, used by Alembic.
revision = "321b4ae75bdf"
down_revision = "28acf3c420b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions_entity_map",
        sa.Column("name", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "permissions_entity_map",
        sa.Column("entitlements", ProEntitlementsType(), nullable=True),
    )
    op.drop_constraint("permissions_entity_map_ibfk_2", "permissions_entity_map", type_="foreignkey")
    op.drop_column("permissions_entity_map", "user_permission_uuid")
    op.drop_table("permissions_user_role_type")
    op.add_column(
        "user",
        sa.Column("pro_entitlements", ProEntitlementsType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pro_entitlements")
    op.add_column(
        "permissions_entity_map",
        sa.Column("user_permission_uuid", sa.BINARY(length=16), nullable=False),
    )
    op.drop_column("permissions_entity_map", "entitlements")
    op.drop_column("permissions_entity_map", "name")
    op.create_table(
        "permissions_user_role_type",
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("uuid", sa.BINARY(length=16), nullable=False),
        sa.Column("created_date", sa.DATETIME(), nullable=True),
        sa.Column("updated_date", sa.DATETIME(), nullable=True),
        sa.Column("entitlements", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_foreign_key(
        "permissions_entity_map_ibfk_2",
        "permissions_entity_map",
        "permissions_user_role_type",
        ["user_permission_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###
