"""Add back item content

Revision ID: 3264ae9747e4
Revises: 99c9eb2cf21f
Create Date: 2024-05-23 12:56:50.035583

"""

import sqlalchemy as sa
from sqlalchemy import func, select, update

from alembic import op  # type: ignore
from api.models.model_helpers import GzipJsonType
from api.models.workspace_models import DashboardItem, DashboardSave

# revision identifiers, used by Alembic.
revision = "3264ae9747e4"
down_revision = "99c9eb2cf21f"
branch_labels = None
depends_on = None


def add_latest_share_to_item():
    conn = op.get_bind()
    subquery = (
        select(DashboardSave.dashboard_item_uuid, func.max(DashboardSave.created_date).label("max_created_date"))
        .group_by(DashboardSave.dashboard_item_uuid)
        .subquery()
    )

    query = select(DashboardSave.dashboard_item_uuid, DashboardSave.content).join(
        subquery,
        (DashboardSave.dashboard_item_uuid == subquery.c.dashboard_item_uuid)
        & (DashboardSave.created_date == subquery.c.max_created_date),
    )

    result = conn.execute(query).all()
    for x in result:
        item = update(DashboardItem).where(DashboardItem.uuid == x[0]).values(content=x[1])
        conn.execute(item)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dashboard_item", sa.Column("content", GzipJsonType, nullable=True))
    add_latest_share_to_item()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dashboard_item", "content")
    # ### end Alembic commands ###
