"""Trakcing whether referred_by sent

Revision ID: 38aef2d3ba48
Revises: d7164fccbdb5
Create Date: 2022-07-22 15:55:16.914848

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "38aef2d3ba48"
down_revision = "d7164fccbdb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("referred_by_sent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "referred_by_sent")
    # ### end Alembic commands ###
