"""Add pro display settings

Revision ID: 3a6218960811
Revises: 6429d610c3a4
Create Date: 2023-12-13 16:09:36.578785

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import ProDisplaySettingsType

# revision identifiers, used by Alembic.
revision = "3a6218960811"
down_revision = "6429d610c3a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("pro_display_settings", ProDisplaySettingsType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pro_display_settings")
    # ### end Alembic commands ###
