"""Script tags

Revision ID: 3f377945656c
Revises: 16d586938d51
Create Date: 2023-05-19 15:53:41.942614

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "3f377945656c"
down_revision = "16d586938d51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("script", sa.Column("tags", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("script", "tags")
    # ### end Alembic commands ###
