"""Added tauri build

Revision ID: 3faba90206e7
Revises: f5b7610a09f2
Create Date: 2022-12-02 14:40:22.866073

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "3faba90206e7"
down_revision = "f5b7610a09f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tauribuild",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=12), nullable=False),
        sa.Column("system", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("pub_date", sa.DateTime(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tauribuild")
    # ### end Alembic commands ###
