"""make user_uuid unique and not nullable

Revision ID: 402c8e1fb30c
Revises: fc3f76a24f2e
Create Date: 2024-07-10 08:20:16.725006

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "402c8e1fb30c"
down_revision = "fc3f76a24f2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "copilot_chats", ["user_uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "copilot_chats", type_="unique")
    # ### end Alembic commands ###
