"""User role entitlements

Revision ID: 42cfca69a34d
Revises: cf33521a47a5
Create Date: 2023-05-03 09:39:12.669795

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "42cfca69a34d"
down_revision = "cf33521a47a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions_user_role_type",
        sa.Column("entitlements", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permissions_user_role_type", "entitlements")
    # ### end Alembic commands ###
