"""Track origin of sessions

Revision ID: 44317fee32e8
Revises: c85675379019
Create Date: 2023-03-01 07:51:15.114500

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "44317fee32e8"
down_revision = "c85675379019"
branch_labels = None
depends_on = None


def upgrade():
    dict_op = op.get_bind().engine.dialect.name
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("api_token", sa.String(length=300), nullable=True))
    if dict_op == "mysql":
        op.drop_index("identifier_date_unqiue", table_name="tauri_log")
    elif dict_op == "postgresql":
        op.drop_constraint("identifier_date_unqiue", "tauri_log", type_="unique")

    op.create_unique_constraint("identifier_date_unique", "tauri_log", ["identifier", "date", "log_type"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("identifier_date_unique", "tauri_log", type_="unique")
    op.create_index(
        "identifier_date_unqiue",
        "tauri_log",
        ["identifier", "date", "log_type"],
        unique=False,
    )
    op.drop_column("session", "api_token")
    # ### end Alembic commands ###
