"""add is_global to storedFile

Revision ID: 44a731205033
Revises: cef1604d8a50
Create Date: 2024-09-11 12:33:58.796302

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "44a731205033"
down_revision = "cef1604d8a50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stored_file", sa.Column("is_global", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stored_file", "is_global")
    # ### end Alembic commands ###
