"""adjustments to data bundle table

Revision ID: 452f62e88dab
Revises: 44a731205033
Create Date: 2024-09-17 15:39:29.499201

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "452f62e88dab"
down_revision = "44a731205033"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_bundle", sa.Column("dashboards_at_launch", sa.JSON(), nullable=True))
    op.add_column("data_bundle", sa.Column("my_dashboards", sa.JSON(), nullable=True))
    op.drop_column("data_bundle", "search")
    op.drop_column("data_bundle", "except_charting")
    op.drop_column("data_bundle", "except_data_connector")
    op.drop_column("data_bundle", "settings")

    # data_bundle.except_dashboard_templates
    op.execute(
        """
        UPDATE data_bundle
        SET except_dashboard_templates = '["etfTemplate"]'
        WHERE bundle_name IN ('Default', 'Equity Research')
        """
    )

    # data_bundle.except_widgets
    op.execute(
        """
        UPDATE data_bundle
        SET except_widgets = '[
            "etf_holdings",
            "economic_calendar",
            "earnings_trends",
            "revenue_trends",
            "etf_classification",
            "etf_characteristics"
        ]'
        WHERE bundle_name IN ('Default', 'Equity Research')
        """
    )
    # data_bundle.except_team_collaboration
    op.execute(
        """
        UPDATE data_bundle
        SET except_team_collaboration = '["pdf_reports","sharing"]'
        WHERE bundle_name = 'Default'
        """
    )
    op.execute(
        """
        UPDATE data_bundle
        SET except_team_collaboration = null
        WHERE bundle_name = 'Equity Research'
        """
    )
    # data_bundle.dashboards_at_launch
    op.execute(
        """
        UPDATE data_bundle
        SET dashboards_at_launch = '["onboarding", "charting", "news", "equity", "equityAnalyst", "calendars"]'
        WHERE bundle_name = 'Default'
        """
    )
    op.execute(
        """
        UPDATE data_bundle
        SET dashboards_at_launch = '["onboarding", "charting", "news", "equity", "analyst", "calendars", "etfTemplate"]'
        WHERE bundle_name = 'Equity Research'
        """
    )
    # data_bundle.my_dashboards
    op.execute(
        """
        UPDATE data_bundle
        SET my_dashboards = '[
            "onboarding",
            "news",
            "charting",
            "equity",
            "equityAnalyst",
            "calendars",
            "countryEconomics"
        ]'
        WHERE bundle_name IN ('Default', 'Equity Research')
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_bundle",
        sa.Column(
            "settings",
            sa.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            nullable=False,
        ),
    )
    op.add_column("data_bundle", sa.Column("except_data_connector", sa.JSON(), nullable=True))
    op.add_column("data_bundle", sa.Column("except_charting", sa.JSON(), nullable=False))
    op.add_column(
        "data_bundle",
        sa.Column(
            "search",
            sa.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            nullable=True,
        ),
    )
    op.drop_column("data_bundle", "my_dashboards")
    op.drop_column("data_bundle", "dashboards_at_launch")
    # ### end Alembic commands ###
