"""add bio column to user

Revision ID: 468c3559b836
Revises: 0ea2826f648a
Create Date: 2023-08-25 14:53:24.719087

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "468c3559b836"
down_revision = "0ea2826f648a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("bio", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "bio")
    # ### end Alembic commands ###
