"""Added entity tables

Revision ID: 4825a66bb7aa
Revises: 73a5106d8ed1
Create Date: 2023-04-06 17:18:26.246926

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "4825a66bb7aa"
down_revision = "73a5106d8ed1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_type",
        sa.Column("_type", sa.String(length=100), nullable=True),
        sa.Column("code", sa.String(length=3), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("permission_hierarchy", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "entity",
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("entity_type_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_type_uuid"],
            ["entity_type.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "entity_relationship",
        sa.Column("parent_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("child_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_uuid"],
            ["entity.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_uuid"],
            ["entity.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity_relationship")
    op.drop_table("entity")
    op.drop_table("entity_type")
    # ### end Alembic commands ###
