"""add widget metadata table

Revision ID: 492f03226213
Revises: c08bd0a7bafa
Create Date: 2024-08-30 14:58:22.935040

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "492f03226213"
down_revision = "c08bd0a7bafa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "widget_metadata",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("sub_category", sa.String(length=50), nullable=False),
        sa.Column("widget_type", sa.String(length=50), nullable=False),
        sa.Column("schema", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.CheckConstraint(
            "widget_type IN ('iframe', 'rss_viewer', 'rich_note')",
            name="widget_type_check",
        ),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"], "widget_metadata_ibfk_1"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("widget_metadata")
    # ### end Alembic commands ###
