"""Create invites

Revision ID: 4ba2b889e403
Revises: 70ce8bebdcc7
Create Date: 2023-11-17 08:16:19.214521

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime

# revision identifiers, used by Alembic.
revision = "4ba2b889e403"
down_revision = "70ce8bebdcc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dashboard_item", "is_group")
    op.alter_column(
        "entity_type",
        "entity_type",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.add_column("user", sa.Column("temporary_password", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("pro_trial_end", AwareDateTime(), nullable=True))
    op.add_column("user", sa.Column("pro_trial_extension", sa.Boolean(), nullable=True))
    op.drop_column("user", "pro_trial_start")
    op.add_column("user_pro_invite", sa.Column("data", sa.JSON(), nullable=True))
    op.drop_column("user_pro_invite", "code")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_pro_invite", sa.Column("code", sa.VARCHAR(length=12), nullable=True))
    op.drop_column("user_pro_invite", "data")
    op.add_column("user", sa.Column("pro_trial_start", sa.DATETIME(), nullable=True))
    op.drop_column("user", "pro_trial_extension")
    op.drop_column("user", "pro_trial_end")
    op.drop_column("user", "temporary_password")
    op.alter_column(
        "entity_type",
        "entity_type",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.add_column(
        "dashboard_item",
        sa.Column(
            "is_group",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
