"""Add script fields

Revision ID: 4ce88fab3add
Revises: 192e2c9ee8cf
Create Date: 2023-02-09 09:53:45.069318

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "4ce88fab3add"
down_revision = "192e2c9ee8cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("script", sa.Column("version", sa.String(length=20), nullable=False))
    op.add_column("script", sa.Column("public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("script", "public")
    op.drop_column("script", "version")
    # ### end Alembic commands ###
