"""Track dashboards that are shared on invites

Revision ID: 4e25caffe677
Revises: 3264ae9747e4
Create Date: 2024-06-10 15:58:10.607688

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "4e25caffe677"
down_revision = "3264ae9747e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("permissions_invite", sa.Column("shared_dashboards", sa.JSON(), nullable=True))
    op.add_column("user_pro_invite", sa.Column("shared_dashboards", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_pro_invite", "shared_dashboards")
    op.drop_column("permissions_invite", "shared_dashboards")
    # ### end Alembic commands ###
