"""Add chargebee transaction columns

Revision ID: 52fbf9c6fb7a
Revises: 0fc20d03e5f7
Create Date: 2022-06-08 17:48:53.858900

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "52fbf9c6fb7a"
down_revision = "0fc20d03e5f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chargebee", sa.Column("transaction_id", sa.String(length=100), nullable=True))
    op.add_column(
        "chargebee",
        sa.Column("transaction_gateway", sa.String(length=100), nullable=True),
    )
    op.add_column("chargebee", sa.Column("transaction_date", sa.DateTime(), nullable=True))
    op.add_column(
        "chargebee",
        sa.Column("transaction_payment_method", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "chargebee",
        sa.Column("transaction_amount", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "chargebee",
        sa.Column("transaction_linked_invoices", sa.String(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chargebee", "transaction_linked_invoices")
    op.drop_column("chargebee", "transaction_amount")
    op.drop_column("chargebee", "transaction_payment_method")
    op.drop_column("chargebee", "transaction_date")
    op.drop_column("chargebee", "transaction_gateway")
    op.drop_column("chargebee", "transaction_id")
    # ### end Alembic commands ###
