"""add date for log

Revision ID: 556b832f5415
Revises: 95a7affbb922
Create Date: 2023-04-05 13:52:10.153152

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "556b832f5415"
down_revision = "95a7affbb922"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log", sa.Column("created_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log", "created_date")
    # ### end Alembic commands ###
