"""rename column api_keys -> providers

Revision ID: 559d401acc3c
Revises: 8dd9ef03c98a
Create Date: 2024-08-28 09:41:48.857169

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "559d401acc3c"
down_revision = "8dd9ef03c98a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_bundle",
        "api_keys",
        new_column_name="providers",
        existing_type=sa.JSON(),
        nullable=True,
    )

    op.execute(
        """
        UPDATE data_bundle
        SET except_widgets = '[
            "etf_holdings",
            "economic_calendar",
            "earnings_trends",
            "Revenue Trends",
            "revenue_trends",
            "etf_classification"
        ]'
        WHERE bundle_name IN ('Default', 'Equity Research')
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_bundle",
        "providers",
        new_column_name="api_keys",
        existing_type=sa.JSON(),
        nullable=True,
    )
    # ### end Alembic commands ###
