"""copilot_chat table to have chats as a list of dict

Revision ID: 569090101767
Revises: 2210e6a21ee2
Create Date: 2024-07-09 17:54:15.999127

"""

# revision identifiers, used by Alembic.
revision = "569090101767"
down_revision = "2210e6a21ee2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
