"""Added features server

Revision ID: 5a20cb978c5d
Revises: c49a1bc108d4
Create Date: 2022-09-14 13:22:30.226111

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "5a20cb978c5d"
down_revision = "c49a1bc108d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("features_server", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "features_server")
    # ### end Alembic commands ###
