"""Added billing active

Revision ID: 5b606deef737
Revises: 6f0eb9dd3dfb
Create Date: 2023-09-14 16:22:51.316588

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "5b606deef737"
down_revision = "6f0eb9dd3dfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("billing_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "billing_active")
    # ### end Alembic commands ###
