"""Make dashitem ownership required

Revision ID: 60219005d82d
Revises: a26f7c700407
Create Date: 2023-08-01 13:40:01.054704

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "60219005d82d"
down_revision = "a26f7c700407"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_dashboard_item_creator_uuid_user", "dashboard_item", type_="foreignkey")
    op.drop_constraint("fk_dashboard_item_owner_uuid_user", "dashboard_item", type_="foreignkey")

    # Make both columns NOT NULL
    op.alter_column(
        "dashboard_item",
        "creator_uuid",
        existing_type=sa.BINARY(length=16),
        nullable=False,
    )
    op.alter_column(
        "dashboard_item",
        "owner_uuid",
        existing_type=sa.BINARY(length=16),
        nullable=False,
    )

    # Recreate the foreign keys
    op.create_foreign_key(
        "fk_dashboard_item_creator_uuid_user",
        "dashboard_item", "user",
        ["creator_uuid"], ["uuid"]
    )
    op.create_foreign_key(
        "fk_dashboard_item_owner_uuid_user",
        "dashboard_item", "user",
        ["owner_uuid"], ["uuid"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_dashboard_item_creator_uuid_user", "dashboard_item", type_="foreignkey")
    op.drop_constraint("fk_dashboard_item_owner_uuid_user", "dashboard_item", type_="foreignkey")

    # Make columns nullable again
    op.alter_column(
        "dashboard_item",
        "owner_uuid",
        existing_type=sa.BINARY(length=16),
        nullable=True,
    )
    op.alter_column(
        "dashboard_item",
        "creator_uuid",
        existing_type=sa.BINARY(length=16),
        nullable=True,
    )

    # Recreate foreign keys
    op.create_foreign_key(
        "fk_dashboard_item_creator_uuid_user",
        "dashboard_item", "user",
        ["creator_uuid"], ["uuid"]
    )
    op.create_foreign_key(
        "fk_dashboard_item_owner_uuid_user",
        "dashboard_item", "user",
        ["owner_uuid"], ["uuid"]
    )
    # ### end Alembic commands ###
