"""make dashboard save compressed

Revision ID: 630413d79906
Revises: e3bb43413f6c
Create Date: 2024-05-31 10:40:38.595375

"""

import sqlalchemy as sa
from sqlalchemy import delete

from alembic import op  # type: ignore
from api.models import DashboardSave
from api.models.model_helpers import GzipJsonType

# revision identifiers, used by Alembic.
revision = "630413d79906"
down_revision = "e3bb43413f6c"
branch_labels = None
depends_on = None


def delete_all_saves():
    conn = op.get_bind()
    query = delete(DashboardSave)
    conn.execute(query)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    delete_all_saves()
    op.alter_column(
        "dashboard_save",
        "content",
        existing_type=sa.JSON(),
        type_=GzipJsonType(),
        existing_nullable=True,
        postgresql_using="content::text::bytea",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dashboard_save",
        "content",
        existing_type=GzipJsonType(),
        type_=sa.JSON(),
        existing_nullable=True,
        postgresql_using="convert_from(content, 'UTF8')::json",
    )
    # ### end Alembic commands ###
