"""Add permissions uuid to pro invite

Revision ID: 6429d610c3a4
Revises: acabb88fa52e
Create Date: 2023-12-12 15:53:16.053328

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "6429d610c3a4"
down_revision = "acabb88fa52e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect_name = op.get_bind().dialect.name
    if dialect_name == "mysql":
        op.drop_index("frontend_id_user_id_unique", table_name="dashboard_tab")
    elif dialect_name == "postgresql":
        op.drop_constraint("frontend_id_user_id_unique", "dashboard_tab", type_="unique")

    op.drop_table("dashboard_tab")
    op.add_column(
        "user_pro_invite",
        sa.Column("permissions_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "user_pro_invite",
        "permissions_entity_map",
        ["permissions_uuid"],
        ["uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_pro_invite", type_="foreignkey")
    op.drop_column("user_pro_invite", "permissions_uuid")
    op.create_table(
        "dashboard_tab",
        sa.Column("uuid", sa.BINARY(length=16), nullable=False),
        sa.Column("frontend_id", sa.VARCHAR(length=200), nullable=False),
        sa.Column("creator_uuid", sa.BINARY(length=16), nullable=True),
        sa.Column("owner_uuid", sa.BINARY(length=16), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("created_date", sa.DATETIME(), nullable=True),
        sa.Column("updated_date", sa.DATETIME(), nullable=True),
        sa.Column(
            "public",
            sa.Boolean(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["creator_uuid"], ["user.uuid"], name="dashboard_tab_ibfk_1"),
        sa.ForeignKeyConstraint(["owner_uuid"], ["user.uuid"], name="dashboard_tab_ibfk_2"),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "frontend_id_user_id_unique",
        "dashboard_tab",
        ["frontend_id", "owner_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###
