"""add github to socials

Revision ID: 64c92d07af72
Revises: 0a1ccb6a2e03
Create Date: 2023-08-07 14:02:37.507863

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "64c92d07af72"
down_revision = "0a1ccb6a2e03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("github", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "github")
    # ### end Alembic commands ###
