"""entitlements

Revision ID: 66642a0d22e9
Revises: c08bd0a7bafa
Create Date: 2024-08-08 12:31:53.550608

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "66642a0d22e9"
down_revision = "c08bd0a7bafa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("has_trial", sa.Boolean(), nullable=False),
        sa.Column("trial_duration_days", sa.Integer(), nullable=True),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "default_tier",
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
        sa.Column("file_upload_size_gb", sa.Integer(), nullable=True),
        sa.Column("share_widgets", sa.String(length=20), nullable=True),
        sa.Column("data_bundle", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_data", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_copilot", sa.Boolean(), nullable=True),
        sa.Column("admin_access", sa.Boolean(), nullable=True),
        sa.Column("support", sa.Boolean(), nullable=True),
        sa.Column("excel_add_in", sa.Boolean(), nullable=True),
        sa.Column("data_add_ons_redistribution", sa.Boolean(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.CheckConstraint(
            "share_widgets IN ('public', 'private')",
            name="check_share_widgets_values_tier_defaults",
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["tier.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "entitlement",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
        sa.Column("file_upload_size_gb", sa.Integer(), nullable=True),
        sa.Column("share_widgets", sa.String(length=20), nullable=True),
        sa.Column("data_bundle", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_data", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_copilot", sa.Boolean(), nullable=True),
        sa.Column("admin_access", sa.Boolean(), nullable=True),
        sa.Column("support", sa.Boolean(), nullable=True),
        sa.Column("excel_add_in", sa.Boolean(), nullable=True),
        sa.Column("data_add_ons_redistribution", sa.Boolean(), nullable=True),
        sa.Column("is_trial", sa.Boolean(), nullable=True),
        sa.Column(
            "trial_expiration_date",
            api.models.model_helpers.AwareDateTime(),
            nullable=True,
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.CheckConstraint(
            "share_widgets IN ('public', 'private')",
            name="check_share_widgets_values_entitlements",
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["tier.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_entitlement_user_uuid"), "entitlement", ["user_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entitlement_user_uuid"), table_name="entitlement")
    op.drop_table("entitlement")
    op.drop_table("default_tier")
    op.drop_table("tier")

    # ### end Alembic commands ###
