"""Add feature column

Revision ID: 6681cee3c064
Revises: a4359edbc6e1
Create Date: 2022-11-07 13:07:04.668505

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "6681cee3c064"
down_revision = "a4359edbc6e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("feature_id", sa.String(length=100), nullable=False),
        sa.Column("votes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feature")
    # ### end Alembic commands ###
