"""add data_bundle table

Revision ID: 6739c286b167
Revises: a43d9da763f1
Create Date: 2024-08-19 09:21:20.885550

"""

from uuid import uuid4

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore
from api import base

# revision identifiers, used by Alembic.
revision = "6739c286b167"
down_revision = "a43d9da763f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    op.create_table(
        "data_bundle",
        sa.Column("bundle_name", sa.String(length=50), nullable=False),
        sa.Column("except_widgets", sa.JSON(), nullable=False),
        sa.Column("except_dashboard_templates", sa.JSON(), nullable=False),
        sa.Column("except_charting", sa.JSON(), nullable=False),
        sa.Column("search", sa.String(length=50), nullable=True),
        sa.Column("settings", sa.String(length=50), nullable=False),
        sa.Column("except_team_collaboration", sa.JSON(), nullable=True),
        sa.Column("excel_add_in", sa.Boolean(), nullable=False),
        sa.Column("data_export", sa.Boolean(), nullable=False),
        sa.Column("except_data_connector", sa.JSON(), nullable=True),
        sa.Column("api_keys", sa.JSON(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.CheckConstraint("search IN ('widget_tab_only', NULL)", name="check_search_bundle"),
        sa.CheckConstraint(
            "settings IN ('remove_default_widget_ticker', NULL)",
            name="check_settings_bundle",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("bundle_name"),
    )

    meta = sa.MetaData()
    tier = sa.Table("data_bundle", meta, autoload_with=op.get_bind())
    op.bulk_insert(
        tier,
        [
            {
                "uuid": uuid4().bytes if dialect == "mysql" else uuid4(),
                "created_date": base.get_now(),
                "updated_date": base.get_now(),
                "bundle_name": "Default",
                "except_widgets": [
                    "ETF Holdings",
                    "Economic Calendar",
                    "Earnings Trends",
                    "Revenue Trends",
                    "ETF Characteristics",
                    "ETF Classification",
                ],
                "except_charting": ["economy"],
                "except_dashboard_templates": ["ETF Template"],
                "search": "widget_tab_only",
                "settings": "remove_default_widget_ticker",
                "except_team_collaboration": ["pdf_reports"],
                "excel_add_in": False,
                "data_export": False,
                "except_data_connector": ["MySQL", "SQLite", "Snowflake"],
                "api_keys": ["fmp", "econdb", "benzinga"],
            },
            {
                "uuid": uuid4().bytes if dialect == "mysql" else uuid4(),
                "created_date": base.get_now(),
                "updated_date": base.get_now(),
                "bundle_name": "Equity Research",
                "except_widgets": [
                    "ETF Holdings",
                    "Economic Calendar",
                    "Earnings Trends",
                    "Revenue Trends",
                    "ETF Characteristics",
                    "ETF Classification",
                ],
                "except_charting": ["economy"],
                "except_dashboard_templates": ["ETF Template"],
                "search": "widget_tab_only",
                "settings": "remove_default_widget_ticker",
                "except_team_collaboration": ["pdf_reports"],
                "excel_add_in": True,
                "data_export": True,
                "except_data_connector": None,
                "api_keys": ["fmp", "econdb", "benzinga"],
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_bundle")
    # ### end Alembic commands ###
