"""add viewed column to shared dashboards

Revision ID: 6bfc3dd05897
Revises: 5217fec04d1a
Create Date: 2024-09-05 09:21:42.979735

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "6bfc3dd05897"
down_revision = "5217fec04d1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dashboard_share", sa.Column("viewed", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dashboard_share", "viewed")
    # ### end Alembic commands ###
