"""add authenticator requirer to entity

Revision ID: 6f0eb9dd3dfb
Revises: e3e2c3066379
Create Date: 2023-09-12 09:34:29.825016

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "6f0eb9dd3dfb"
down_revision = "e3e2c3066379"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("require_authenticator", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "require_authenticator")
    # ### end Alembic commands ###
