"""Added terminal style column

Revision ID: 6fe17636f05a
Revises: eb9e51e4c4d0
Create Date: 2023-03-14 13:23:14.232943

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "6fe17636f05a"
down_revision = "eb9e51e4c4d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("features_terminal_style", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "features_terminal_style")
    # ### end Alembic commands ###
