"""Added pro user fields

Revision ID: 70ce8bebdcc7
Revises: 73a058ef084f
Create Date: 2023-11-10 14:25:43.410453

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime

# revision identifiers, used by Alembic.
revision = "70ce8bebdcc7"
down_revision = "73a058ef084f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_pro_invite",
        sa.Column("inviting_user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=True),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["inviting_user_uuid"], ["user.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.add_column("user", sa.Column("pro_trial_start", AwareDateTime(), nullable=True))
    op.add_column("user", sa.Column("pro_trial_renewals", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("pro_start", AwareDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pro_start")
    op.drop_column("user", "pro_trial_renewals")
    op.drop_column("user", "pro_trial_start")
    op.drop_table("user_pro_invite")
    # ### end Alembic commands ###
