"""Added pos user

Revision ID: 73a058ef084f
Revises: 321b4ae75bdf
Create Date: 2023-11-09 16:07:05.718788

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "73a058ef084f"
down_revision = "321b4ae75bdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("accepted_pro_tos", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "accepted_pro_tos")
    # ### end Alembic commands ###
