"""make dates standardized

Revision ID: 73a5106d8ed1
Revises: 556b832f5415
Create Date: 2023-04-06 16:05:03.097691

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "73a5106d8ed1"
down_revision = "556b832f5415"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("change", sa.Column("updated_date", sa.DateTime(), nullable=True))
    op.add_column(
        "chargebee",
        sa.Column("updated_date", sa.DateTime(), nullable=True),
    )
    op.add_column("feature", sa.Column("created_date", sa.DateTime(), nullable=True))
    op.add_column("feature", sa.Column("updated_date", sa.DateTime(), nullable=True))
    op.add_column("log", sa.Column("updated_date", sa.DateTime(), nullable=True))
    op.add_column("login", sa.Column("updated_date", sa.DateTime(), nullable=True))
    op.add_column(
        "pro_download",
        sa.Column("updated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "reconciliation",
        sa.Column("updated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "script_upvote",
        sa.Column("updated_date", sa.DateTime(), nullable=True),
    )
    op.alter_column("script_upvote", "created_date", existing_type=sa.DATETIME(), nullable=True)
    op.add_column("session", sa.Column("updated_date", sa.DateTime(), nullable=True))
    op.add_column(
        "tauri_log",
        sa.Column("created_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "tauri_log",
        sa.Column("updated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "tauribuild",
        sa.Column("created_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "tauribuild",
        sa.Column("updated_date", sa.DateTime(), nullable=True),
    )
    op.add_column("user", sa.Column("updated_date", sa.DateTime(), nullable=True))
    op.add_column("webhook", sa.Column("created_date", sa.DateTime(), nullable=True))
    op.add_column("webhook", sa.Column("updated_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook", "updated_date")
    op.drop_column("webhook", "created_date")
    op.drop_column("user", "updated_date")
    op.drop_column("tauribuild", "updated_date")
    op.drop_column("tauribuild", "created_date")
    op.drop_column("tauri_log", "updated_date")
    op.drop_column("tauri_log", "created_date")
    op.drop_column("session", "updated_date")
    op.alter_column("script_upvote", "created_date", existing_type=sa.DATETIME(), nullable=False)
    op.drop_column("script_upvote", "updated_date")
    op.drop_column("reconciliation", "updated_date")
    op.drop_column("pro_download", "updated_date")
    op.drop_column("login", "updated_date")
    op.drop_column("log", "updated_date")
    op.drop_column("feature", "updated_date")
    op.drop_column("feature", "created_date")
    op.drop_column("chargebee", "updated_date")
    op.drop_column("change", "updated_date")
    # ### end Alembic commands ###
