"""entitlements for entities

Revision ID: 740cfe7ffd18
Revises: 1d192ffa1f0c
Create Date: 2024-08-22 08:29:35.247186

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "740cfe7ffd18"
down_revision = "1d192ffa1f0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_entitlement",
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
        sa.Column("share_widgets", sa.String(length=20), nullable=True),
        sa.Column("data_bundle", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_data", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_copilot", sa.Boolean(), nullable=True),
        sa.Column("admin_access", sa.Boolean(), nullable=True),
        sa.Column("support", sa.Boolean(), nullable=True),
        sa.Column("excel_add_in", sa.Boolean(), nullable=True),
        sa.Column("data_add_ons_redistribution", sa.Boolean(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.CheckConstraint(
            "share_widgets IN ('public', 'private')",
            name="check_share_widgets_values_entity_entitlements",
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["tier.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_entity_entitlement_entity_uuid"),
        "entity_entitlement",
        ["entity_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entity_entitlement_entity_uuid"), table_name="entity_entitlement")
    op.drop_table("entity_entitlement")
    # ### end Alembic commands ###
