"""add id column and change meta->storage

Revision ID: 74f7d00f54bd
Revises: 944bbc9e26d2
Create Date: 2024-09-02 17:17:25.275477

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models.model_helpers import GzipJsonType, get_mediumblob  # type: ignore

# revision identifiers, used by Alembic.
revision = "74f7d00f54bd"
down_revision = "944bbc9e26d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "widget_metadata",
        sa.Column("storage", GzipJsonType(), nullable=True),
    )
    op.add_column(
        "widget_metadata",
        sa.Column("widget_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    )
    op.drop_column("widget_metadata", "meta")
    # ### end Alembic commands ###


def downgrade():
    dialect = op.get_bind().dialect.name
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("widget_metadata", sa.Column("meta", get_mediumblob(dialect), nullable=True))
    op.drop_column("widget_metadata", "widget_id")
    op.drop_column("widget_metadata", "storage")
    # ### end Alembic commands ###
