"""Add Pro Info

Revision ID: 76f58b355a79
Revises: 3f377945656c
Create Date: 2023-05-19 16:45:43.455454

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "76f58b355a79"
down_revision = "3f377945656c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("features_pro_info", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "features_pro_info")
    # ### end Alembic commands ###
