"""add invite_your_colleagues column to data_bundles table

Revision ID: 77ae861c5ac1
Revises: 452f62e88dab
Create Date: 2024-09-17 18:07:12.670578

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "77ae861c5ac1"
down_revision = "452f62e88dab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_bundle",
        sa.Column("invite_your_colleagues", sa.Boolean(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_bundle", "invite_your_colleagues")
    # ### end Alembic commands ###
