"""Track email we miss you

Revision ID: 8015f480816c
Revises: c78bb503304f
Create Date: 2024-01-05 15:08:13.525059

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "8015f480816c"
down_revision = "c78bb503304f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("pro_inactivity_email_sent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pro_inactivity_email_sent")
    # ### end Alembic commands ###
