"""add stored_file and make uuids index

Revision ID: 8457325b0f24
Revises: 402c8e1fb30c
Create Date: 2024-07-26 12:01:59.248921

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models import model_helpers  # type: ignore

# revision identifiers, used by Alembic.
revision = "8457325b0f24"
down_revision = "402c8e1fb30c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_file",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("s3_file_name", sa.Text(), nullable=False),
        sa.Column("original_file_name", sa.Text(), nullable=True),
        sa.Column("extension", sa.Text(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.Text(), nullable=False),
        sa.Column("creater_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("file_widget_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creater_uuid"],
            ["user.uuid"],
        ),
        sa.ForeignKeyConstraint(["file_widget_uuid"], ["file_widget.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_api_source_user_uuid"), "api_source", ["user_uuid"], unique=False)
    op.create_index(op.f("ix_dashboard_item_creator_uuid"), "dashboard_item", ["creator_uuid"], unique=False)
    op.create_index(op.f("ix_dashboard_item_owner_uuid"), "dashboard_item", ["owner_uuid"], unique=False)
    op.create_index(
        op.f("ix_dashboard_save_dashboard_item_uuid"), "dashboard_save", ["dashboard_item_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_dashboard_share_dashboard_item_uuid"), "dashboard_share", ["dashboard_item_uuid"], unique=False
    )
    op.create_index(op.f("ix_dashboard_share_shared_user_uuid"), "dashboard_share", ["shared_user_uuid"], unique=False)
    op.create_index(op.f("ix_entity_entity_type_uuid"), "entity", ["entity_type_uuid"], unique=False)
    op.create_index(op.f("ix_entity_relationship_child_uuid"), "entity_relationship", ["child_uuid"], unique=False)
    op.create_index(op.f("ix_entity_relationship_parent_uuid"), "entity_relationship", ["parent_uuid"], unique=False)
    op.create_index(op.f("ix_entity_relationship_supreme_uuid"), "entity_relationship", ["supreme_uuid"], unique=False)
    op.create_index(op.f("ix_file_widget_user_uuid"), "file_widget", ["user_uuid"], unique=False)
    op.create_index(op.f("ix_login_user_uuid"), "login", ["user_uuid"], unique=False)
    op.create_index(
        op.f("ix_permissions_entity_map_entity_uuid"), "permissions_entity_map", ["entity_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_permissions_invite_permissions_uuid"), "permissions_invite", ["permissions_uuid"], unique=False
    )
    op.create_index(op.f("ix_permissions_invite_user_uuid"), "permissions_invite", ["user_uuid"], unique=False)
    op.create_index(op.f("ix_pro_download_user_uuid"), "pro_download", ["user_uuid"], unique=False)
    op.create_index(op.f("ix_session_user_uuid"), "session", ["user_uuid"], unique=False)
    op.create_index(op.f("ix_single_widget_user_uuid"), "single_widget", ["user_uuid"], unique=False)
    op.create_index(
        op.f("ix_user_pro_invite_inviting_user_uuid"), "user_pro_invite", ["inviting_user_uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_pro_invite_inviting_user_uuid"), table_name="user_pro_invite")
    op.drop_index(op.f("ix_single_widget_user_uuid"), table_name="single_widget")
    op.drop_index(op.f("ix_session_user_uuid"), table_name="session")
    op.drop_index(op.f("ix_pro_download_user_uuid"), table_name="pro_download")
    op.drop_index(op.f("ix_permissions_invite_user_uuid"), table_name="permissions_invite")
    op.drop_index(op.f("ix_permissions_invite_permissions_uuid"), table_name="permissions_invite")
    op.drop_index(op.f("ix_permissions_entity_map_entity_uuid"), table_name="permissions_entity_map")
    op.drop_index(op.f("ix_login_user_uuid"), table_name="login")
    op.drop_index(op.f("ix_file_widget_user_uuid"), table_name="file_widget")
    op.drop_index(op.f("ix_entity_relationship_supreme_uuid"), table_name="entity_relationship")
    op.drop_index(op.f("ix_entity_relationship_parent_uuid"), table_name="entity_relationship")
    op.drop_index(op.f("ix_entity_relationship_child_uuid"), table_name="entity_relationship")
    op.drop_index(op.f("ix_entity_entity_type_uuid"), table_name="entity")
    op.drop_index(op.f("ix_dashboard_share_shared_user_uuid"), table_name="dashboard_share")
    op.drop_index(op.f("ix_dashboard_share_dashboard_item_uuid"), table_name="dashboard_share")
    op.drop_index(op.f("ix_dashboard_save_dashboard_item_uuid"), table_name="dashboard_save")
    op.drop_index(op.f("ix_dashboard_item_owner_uuid"), table_name="dashboard_item")
    op.drop_index(op.f("ix_dashboard_item_creator_uuid"), table_name="dashboard_item")
    op.drop_index(op.f("ix_api_source_user_uuid"), table_name="api_source")
    op.drop_table("stored_file")
    # ### end Alembic commands ###
