"""developer onboarding table

Revision ID: 86e944acc97c
Revises: c08bd0a7bafa
Create Date: 2024-08-05 09:59:49.590389

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "86e944acc97c"
down_revision = "c08bd0a7bafa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "developer_onboarding",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("primary_usage", sa.Text(), nullable=True),
        sa.Column("organization_type", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("programming_experience", sa.Text(), nullable=True),
        sa.Column("data_types", sa.JSON(), nullable=True),
        sa.Column("other_data_types", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_developer_onboarding_user_uuid"),
        "developer_onboarding",
        ["user_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_developer_onboarding_user_uuid"), table_name="developer_onboarding")
    op.drop_table("developer_onboarding")
    # ### end Alembic commands ###
