"""Add a clean_email user item

Revision ID: 874b29e54a32
Revises: 20f8ab217c97
Create Date: 2024-04-25 14:19:45.351125

"""

import sqlalchemy as sa
from sqlalchemy import BigInteger, Column, select, update
from sqlalchemy_utils.types.email import EmailType

from alembic import op  # type: ignore
from api.base import clean_email
from api.models import User

# revision identifiers, used by Alembic.
revision = "874b29e54a32"
down_revision = "20f8ab217c97"
branch_labels = None
depends_on = None


def add_clean_emails():
    conn = op.get_bind()
    select_query = select(User.email, User.uuid).where(User.clean_email.is_(None))
    result = conn.execute(select_query).all()
    for email, uuid in result:
        try:
            cleaned = clean_email(email)
        except ValueError:
            cleaned = ""
        update_query = update(User).values(clean_email=cleaned).where(User.uuid == uuid)
        conn.execute(update_query)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", Column("clean_email", EmailType(length=255), nullable=True))
    add_clean_emails()
    op.alter_column("user", "clean_email", existing_type=EmailType(length=255), nullable=False)
    op.alter_column("user", "hubspot_id", existing_type=sa.INTEGER(), type_=BigInteger(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "clean_email")
    op.alter_column("user", "hubspot_id", existing_type=BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    # ### end Alembic commands ###
