"""change _type

Revision ID: 87b9b8c2a03d
Revises: 918f48e2ca1d
Create Date: 2023-04-07 15:44:00.525637

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "87b9b8c2a03d"
down_revision = "918f48e2ca1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity_type", sa.Column("entity_type", sa.String(length=100), nullable=True))
    op.drop_column("entity_type", "_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entity_type",
        sa.Column(
            "_type",
            sa.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
            nullable=True,
        ),
    )
    op.drop_column("entity_type", "entity_type")
    # ### end Alembic commands ###
