"""User auth tokens

Revision ID: 88b4fc7d8529
Revises: c619a792d8d8
Create Date: 2023-01-18 14:08:28.710262

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "88b4fc7d8529"
down_revision = "c619a792d8d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("json_token", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("auth_token", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "auth_token")
    op.drop_column("user", "json_token")
    # ### end Alembic commands ###
