"""tauri_item_type

Revision ID: 8ac319a2101b
Revises: 04c0080fee5a
Create Date: 2023-03-23 08:58:27.755706

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "8ac319a2101b"
down_revision = "04c0080fee5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tauribuild", sa.Column("item_type", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tauribuild", "item_type")
    # ### end Alembic commands ###
