"""Add seats and an end date to entity

Revision ID: 8dbbec2fc303
Revises: 25add7f11619
Create Date: 2024-04-08 12:47:05.934368

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime

# revision identifiers, used by Alembic.
revision = "8dbbec2fc303"
down_revision = "25add7f11619"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("seats", sa.Integer(), nullable=True))
    op.add_column("entity", sa.Column("expiration_date", AwareDateTime(), nullable=True))
    op.add_column("entity", sa.Column("stripe_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "stripe_id")
    op.drop_column("entity", "expiration_date")
    op.drop_column("entity", "seats")
    # ### end Alembic commands ###
