"""fix in data bundles columns

Revision ID: 8dd9ef03c98a
Revises: c2b83acdba36
Create Date: 2024-08-27 10:19:18.431075

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "8dd9ef03c98a"
down_revision = "c2b83acdba36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entity_entitlement",
        sa.Column("data_bundle_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    )
    op.create_foreign_key(None, "entity_entitlement", "data_bundle", ["data_bundle_uuid"], ["uuid"])
    op.drop_column("entity_entitlement", "data_bundle")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entity_entitlement",
        sa.Column(
            "data_bundle",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "entity_entitlement", type_="foreignkey")
    op.drop_column("entity_entitlement", "data_bundle_uuid")
    # ### end Alembic commands ###
