"""make code unique

Revision ID: 918f48e2ca1d
Revises: 4825a66bb7aa
Create Date: 2023-04-07 14:25:13.025390

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "918f48e2ca1d"
down_revision = "4825a66bb7aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "entity_type",
        "code",
        existing_type=sa.VARCHAR(collation="utf8mb4_unicode_ci", length=3),
        nullable=False,
    )
    op.create_unique_constraint(None, "entity_type", ["code"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "entity_type", type_="unique")
    op.alter_column(
        "entity_type",
        "code",
        existing_type=sa.VARCHAR(collation="utf8mb4_unicode_ci", length=3),
        nullable=True,
    )
    # ### end Alembic commands ###
