"""Expand dashboard item

Revision ID: 92691458cffb
Revises: 0adbf87d25e9
Create Date: 2023-07-31 13:38:56.775699

"""

import sqlalchemy as sa
from sqlalchemy_utils.types.uuid import UUIDType

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "92691458cffb"
down_revision = "0adbf87d25e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dashboard_item", sa.Column("creator_uuid", UUIDType(), nullable=True))
    op.add_column("dashboard_item", sa.Column("owner_uuid", UUIDType(), nullable=True))
    op.add_column("dashboard_item", sa.Column("is_group", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "dashboard_item", "user", ["creator_uuid"], ["uuid"])
    op.create_foreign_key(None, "dashboard_item", "user", ["owner_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dashboard_item", type_="foreignkey")
    op.drop_constraint(None, "dashboard_item", type_="foreignkey")
    op.drop_column("dashboard_item", "is_group")
    op.drop_column("dashboard_item", "owner_uuid")
    op.drop_column("dashboard_item", "creator_uuid")
    # ### end Alembic commands ###
