"""rename column: schema -> meta;  and add constraint: unique combination of user_uuid,name and widget_type

Revision ID: 944bbc9e26d2
Revises: 492f03226213
Create Date: 2024-08-30 18:34:49.866010

"""

import sqlalchemy as sa

from alembic import op
from api.models.model_helpers import GzipJsonType, get_mediumblob  # type: ignore

# revision identifiers, used by Alembic.
revision = "944bbc9e26d2"
down_revision = "492f03226213"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "widget_metadata",
        sa.Column("meta", GzipJsonType(), nullable=True),
    )
    op.create_unique_constraint("uix_user_name_type", "widget_metadata", ["user_uuid", "name", "widget_type"])
    op.drop_column("widget_metadata", "schema")
    # ### end Alembic commands ###


def downgrade():
    dialect = op.get_bind().dialect.name
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("widget_metadata", sa.Column("schema", get_mediumblob(dialect), nullable=True))
    op.drop_constraint("uix_user_name_type", "widget_metadata", type_="unique")
    op.drop_column("widget_metadata", "meta")
    # ### end Alembic commands ###
