"""script created and updated

Revision ID: 95a7affbb922
Revises: 8ac319a2101b
Create Date: 2023-03-29 08:14:24.345709

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "95a7affbb922"
down_revision = "8ac319a2101b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("script", sa.Column("created_date", sa.DateTime(), nullable=True))
    op.add_column("script", sa.Column("updated_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("script", "updated_date")
    op.drop_column("script", "created_date")
    # ### end Alembic commands ###
