"""Track a user's latest pro version

Revision ID: 9988e8e8d51f
Revises: 1b9afb4d6f15
Create Date: 2024-02-26 14:32:58.908853

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "9988e8e8d51f"
down_revision = "1b9afb4d6f15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("latest_version", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "latest_version")
    # ### end Alembic commands ###
