"""Add dashboard versions and sharing

Revision ID: 99c9eb2cf21f
Revises: 874b29e54a32
Create Date: 2024-02-27 08:11:00.857829

"""

import json

import sqlalchemy as sa
from sqlalchemy import insert, text
from sqlalchemy_utils.types.uuid import UUIDType

from alembic import op  # type: ignore
from api.models import DashboardSave
from api.models.model_helpers import DATETIME, AwareDateTime

# revision identifiers, used by Alembic.
revision = "99c9eb2cf21f"
down_revision = "874b29e54a32"
branch_labels = None
depends_on = None


def move_content_to_dashboard_save(op):
    conn = op.get_bind()
    select_query = "SELECT uuid, content FROM dashboard_item"
    result = conn.execute(text(select_query))
    to_insert = []
    for row in result:
        content = None if row[1] is None else json.loads(row[1])
        data = {"dashboard_item_uuid": row[0], "content": content}
        to_insert.append(data)
    if to_insert:
        conn.execute(insert(DashboardSave), to_insert)


def move_content_to_dashboard_item(op):
    conn = op.get_bind()
    select_query = """
        SELECT ds.dashboard_item_uuid, ds.content
        FROM dashboard_save ds
        INNER JOIN (
            SELECT dashboard_item_uuid, MAX(created_date) as max_created_date
            FROM dashboard_save
            GROUP BY dashboard_item_uuid
        ) as latest_save ON ds.dashboard_item_uuid = latest_save.dashboard_item_uuid
        AND ds.created_date = latest_save.max_created_date
    """
    result = conn.execute(text(select_query))
    for row in result:
        update_query = text(
            """
            UPDATE dashboard_item
            SET content = :content
            WHERE uuid = :uuid
        """
        )
        conn.execute(update_query, {"uuid": row[0], "content": row[1]})


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_save",
        sa.Column("dashboard_item_uuid", UUIDType(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.Column("uuid", UUIDType(), nullable=False),
        sa.Column("created_date", DATETIME(fsp=6), nullable=True),
        sa.Column("updated_date", DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["dashboard_item_uuid"], ["dashboard_item.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "dashboard_share",
        sa.Column("dashboard_item_uuid", UUIDType(), nullable=False),
        sa.Column("shared_user_uuid", UUIDType(), nullable=False),
        sa.Column("active", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "permissions",
            sa.Enum("view", "comment", "edit", name="permissionenum"),
            nullable=False,
        ),
        sa.Column("uuid", UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dashboard_item_uuid"], ["dashboard_item.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["shared_user_uuid"], ["user.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.add_column(
        "dashboard_item", sa.Column("entity_share", sa.Boolean(), nullable=False)
    )
    move_content_to_dashboard_save(op)
    op.drop_column("dashboard_item", "content")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dashboard_item", sa.Column("content", sa.JSON(), nullable=True))
    move_content_to_dashboard_item(op)
    op.drop_column("dashboard_item", "entity_share")
    op.drop_table("dashboard_share")
    op.drop_table("dashboard_save")
    # ### end Alembic commands ###
