"""populate data bundles for free trial; update other values

Revision ID: 9ac3a287ad86
Revises: c23b912d4f38
Create Date: 2024-09-18 09:04:25.560626

"""

from uuid import uuid4

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "9ac3a287ad86"
down_revision = "c23b912d4f38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_bundle",
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
    )
    op.add_column(
        "data_bundle",
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
    )

    # Update default_tier with number_copilot_calls_day and total_file_upload_size_gb
    op.execute(
        """
        UPDATE default_tier SET number_copilot_calls_day = 20, total_file_upload_size_gb = 1 WHERE name = 'TerminalDefaults'
    """
    )

    # Update data_bundle
    op.execute(
        """
        UPDATE data_bundle
        SET
            except_widgets = '[]',
            except_dashboard_templates = '[]',
            number_copilot_calls_day = 100,
            total_file_upload_size_gb = 10,
            providers = NULL
        WHERE bundle_name = 'Equity Research'
    """
    )
    op.execute(
        """
        UPDATE data_bundle SET number_copilot_calls_day = 20, total_file_upload_size_gb = 1 WHERE bundle_name = 'Default'
    """
    )
    data_bundle = sa.table(
        "data_bundle",
        sa.column("uuid", sqlalchemy_utils.types.uuid.UUIDType()),
        sa.column("created_date", sa.DateTime()),
        sa.column("updated_date", sa.DateTime()),
        sa.column("bundle_name", sa.String()),
        sa.column("except_widgets", sa.JSON()),
        sa.column("except_dashboard_templates", sa.JSON()),
        sa.column("except_team_collaboration", sa.JSON()),
        sa.column("excel_add_in", sa.Boolean()),
        sa.column("data_export", sa.Boolean()),
        sa.column("providers", sa.JSON()),
        sa.column("dashboards_at_launch", sa.JSON()),
        sa.column("my_dashboards", sa.JSON()),
        sa.column("invite_your_colleagues", sa.Boolean()),
        sa.column("number_copilot_calls_day", sa.Integer()),
        sa.column("total_file_upload_size_gb", sa.Integer()),
    )

    op.execute(
        data_bundle.insert().values(
            uuid=uuid4(),
            created_date=sa.func.now(),
            updated_date=sa.func.now(),
            bundle_name="Pro Trial",
            except_widgets=[
                "etf_holdings",
                "economic_calendar",
                "earnings_trends",
                "revenue_trends",
                "etf_classification",
                "etf_characteristics",
            ],
            except_dashboard_templates=["etfTemplate"],
            except_team_collaboration=None,
            excel_add_in=True,
            data_export=True,
            providers=["fmp", "econdb", "benzinga"],
            dashboards_at_launch=[
                "onboarding",
                "charting",
                "news",
                "equity",
                "equityAnalyst",
                "calendars",
            ],
            my_dashboards=[
                "onboarding",
                "news",
                "charting",
                "equity",
                "equityAnalyst",
                "calendars",
                "countryEconomics",
            ],
            invite_your_colleagues=False,
            number_copilot_calls_day=100,
            total_file_upload_size_gb=10,
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_bundle", "total_file_upload_size_gb")
    op.drop_column("data_bundle", "number_copilot_calls_day")
    # ### end Alembic commands ###
