"""Add feedback table

Revision ID: a26f7c700407
Revises: 92691458cffb
Create Date: 2023-08-01 10:55:49.761726

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime

# revision identifiers, used by Alembic.
revision = "a26f7c700407"
down_revision = "92691458cffb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("emoji", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    # ### end Alembic commands ###
