"""Change is_terminal to source

Revision ID: a4359edbc6e1
Revises: 1eaaedd86b49
Create Date: 2022-10-28 18:30:34.379223

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "a4359edbc6e1"
down_revision = "1eaaedd86b49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login", sa.Column("source", sa.String(length=20), nullable=True))
    op.drop_column("login", "is_terminal")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "login",
        sa.Column(
            "is_terminal",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("login", "source")
    # ### end Alembic commands ###
