"""rename column: file_upload_size_gb -> total_file_upload_size_gb

Revision ID: a43d9da763f1
Revises: 7afeedd5bbf7
Create Date: 2024-08-16 11:35:59.267431

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api import base
from api.models.tier_models import Tier, TierDefaults

# revision identifiers, used by Alembic.
revision = "a43d9da763f1"
down_revision = "7afeedd5bbf7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "default_tier",
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
    )
    op.drop_column("default_tier", "file_upload_size_gb")
    op.add_column(
        "entitlement",
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
    )
    op.drop_column("entitlement", "file_upload_size_gb")

    # Drop content of `tier_defaults` table
    op.execute("DELETE FROM default_tier")

    # Drop content of `tier` table
    op.execute("DELETE FROM tier")

    # Insert contents of Tier and TierDefaults
    op.execute(
        sa.insert(Tier).values(
            [
                {
                    "id": 1,
                    "name": "Pro",
                    "has_trial": True,
                    "trial_duration_days": 21,
                    "created_date": base.get_now(),
                    "updated_date": base.get_now(),
                },
                {
                    "id": 2,
                    "name": "Terminal",
                    "has_trial": False,
                    "trial_duration_days": None,
                    "created_date": base.get_now(),
                    "updated_date": base.get_now(),
                },
            ],
        )
    )

    op.execute(
        sa.insert(TierDefaults).values(
            [
                {
                    "tier_id": 2,
                    "name": "TerminalDefaults",
                    "number_copilot_calls_day": 50,
                    "total_file_upload_size_gb": 5,
                    "share_widgets": "public",
                    "data_bundle": False,
                    "bring_your_own_data": False,
                    "bring_your_own_copilot": False,
                    "admin_access": False,
                    "support": False,
                    "excel_add_in": False,
                    "data_add_ons_redistribution": False,
                    "created_date": base.get_now(),
                    "updated_date": base.get_now(),
                },
                {
                    "tier_id": 1,
                    "name": "ProDefaults",
                    "number_copilot_calls_day": 100,
                    "total_file_upload_size_gb": 50,
                    "share_widgets": "private",
                    "data_bundle": True,
                    "bring_your_own_data": True,
                    "bring_your_own_copilot": True,
                    "admin_access": True,
                    "support": True,
                    "excel_add_in": True,
                    "data_add_ons_redistribution": True,
                    "created_date": base.get_now(),
                    "updated_date": base.get_now(),
                },
            ]
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entitlement",
        sa.Column("file_upload_size_gb", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("entitlement", "total_file_upload_size_gb")
    op.add_column(
        "default_tier",
        sa.Column("file_upload_size_gb", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("default_tier", "total_file_upload_size_gb")
    # ### end Alembic commands ###
