"""Add source to session

Revision ID: a780982dbd27
Revises: 8015f480816c
Create Date: 2024-01-19 08:09:50.362193

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "a780982dbd27"
down_revision = "8015f480816c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("source", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "source")
    # ### end Alembic commands ###
