"""Added Dashboard table

Revision ID: aa64fc3ce944
Revises: 4ce88fab3add
Create Date: 2023-02-20 08:42:20.113888

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models.model_helpers import DATETIME  # type: ignore

# revision identifiers, used by Alembic.
revision = "aa64fc3ce944"
down_revision = "4ce88fab3add"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_tab",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("frontend_id", sa.String(length=200), nullable=False),
        sa.Column("creator_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("owner_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_date", DATETIME(), nullable=True),
        sa.Column("updated_date", DATETIME(), nullable=True),
        sa.Column("public", sa.BOOLEAN(), nullable=False),
        sa.ForeignKeyConstraint(["creator_uuid"], ["user.uuid"]),
        sa.ForeignKeyConstraint(["owner_uuid"], ["user.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_unique_constraint("frontend_id_user_id_unique", "dashboard_tab", ["frontend_id", "owner_uuid"])
    op.alter_column("change", "target_uuid", existing_type=sa.BINARY(length=16), nullable=True)
    op.alter_column("script_upvote", "created_date", existing_type=DATETIME(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("script_upvote", "created_date", existing_type=DATETIME(), nullable=True)
    op.alter_column("change", "target_uuid", existing_type=sa.BINARY(length=16), nullable=False)
    op.drop_constraint("dash_name_user_id_unique", "dashboard_tab", type_="unique")
    op.drop_table("dashboard_tab")
    # ### end Alembic commands ###
