"""Add totp secret

Revision ID: acabb88fa52e
Revises: f68cbfa1d80d
Create Date: 2023-11-30 13:42:36.223575

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "acabb88fa52e"
down_revision = "f68cbfa1d80d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("pro", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("totp_secret", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "totp_secret")
    op.drop_column("session", "pro")
    # ### end Alembic commands ###
