"""total_file_upload_size_gb_count to float

Revision ID: ae65c3641b17
Revises: bc561917bc69
Create Date: 2024-08-22 16:26:28.408143

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "ae65c3641b17"
down_revision = "bc561917bc69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "entitlement_usage",
        "total_file_upload_size_gb_count",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "entitlement_usage",
        "total_file_upload_size_gb_count",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
