"""Add api source table

Revision ID: b098ccf00935
Revises: b191cf5a1a64
Create Date: 2023-12-15 13:37:57.363999

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime

# revision identifiers, used by Alembic.
revision = "b098ccf00935"
down_revision = "b191cf5a1a64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_source",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_source")
    # ### end Alembic commands ###
