"""first

Revision ID: b19d0b637d08
Revises:
Create Date: 2022-06-07 15:05:59.132109

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "b19d0b637d08"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=True),
        sa.Column("change_type", sa.String(length=100), nullable=True),
        sa.Column("target_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("target_column", sa.String(length=100), nullable=True),
        sa.Column("before", sa.String(length=1000), nullable=True),
        sa.Column("after", sa.String(length=1000), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "plan",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("chargebee_plan_id", sa.String(length=50), nullable=True),
        sa.Column("external_name", sa.String(length=128), nullable=False),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("popular", sa.Boolean(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("item_type", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("currency_code", sa.String(length=5), nullable=True),
        sa.Column("period_unit", sa.String(length=10), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "reconciliation",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("chargebee_subscription_id", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("next_bill_date", sa.DateTime(), nullable=True),
        sa.Column("user_uuid", sa.String(length=50), nullable=True),
        sa.Column("plans", sa.String(length=1000), nullable=True),
        sa.Column("source", sa.String(length=15), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "user",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("chargebee_user_id", sa.String(length=50), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("locale", sa.String(length=100), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("alerts_count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("campaign_source", sa.String(length=100), nullable=True),
        sa.Column("referred_by", sa.String(length=100), nullable=True),
        sa.Column("promo_code", sa.String(length=100), nullable=True),
        sa.Column("referral_code", sa.String(length=100), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("referral_code"),
    )
    op.create_table(
        "login",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column(
            "ip_address",
            sqlalchemy_utils.types.ip_address.IPAddressType(length=50),
            nullable=True,
        ),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "subscription",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("chargebee_subscription_id", sa.String(length=50), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("paid_date", sa.DateTime(), nullable=True),
        sa.Column("next_bill_date", sa.DateTime(), nullable=True),
        sa.Column("cancel_date", sa.DateTime(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=1000), nullable=True),
        sa.Column("is_group", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("chargebee_subscription_id"),
    )
    op.create_table(
        "platform",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("subscription_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("platform_id", sa.String(length=129), nullable=False),
        sa.Column("is_group", sa.Boolean(), nullable=True),
        sa.Column("monthly_freecommand", sa.Integer(), nullable=False),
        sa.Column("monthly_reset_date", sa.DateTime(), nullable=True),
        sa.Column("daily_freecommand", sa.Integer(), nullable=False),
        sa.Column("daily_reset_date", sa.DateTime(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_uuid"],
            ["subscription.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "sub_plan",
        sa.Column("subscription_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("plan_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_uuid"],
            ["plan.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_uuid"],
            ["subscription.uuid"],
        ),
        sa.PrimaryKeyConstraint("subscription_uuid", "plan_uuid"),
    )
    op.create_table(
        "transaction",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("subscription_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("cancel_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_uuid"],
            ["subscription.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "trans_plan",
        sa.Column("transaction_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("plan_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_uuid"],
            ["plan.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_uuid"],
            ["transaction.uuid"],
        ),
        sa.PrimaryKeyConstraint("transaction_uuid", "plan_uuid"),
    )
    op.create_table(
        "webhook",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("platform_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["platform_uuid"],
            ["platform.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webhook")
    op.drop_table("trans_plan")
    op.drop_table("transaction")
    op.drop_table("sub_plan")
    op.drop_table("platform")
    op.drop_table("subscription")
    op.drop_table("login")
    op.drop_table("user")
    op.drop_table("reconciliation")
    op.drop_table("plan")
    op.drop_table("change")
    # ### end Alembic commands ###
