"""add permissions

Revision ID: b317896e8655
Revises: 1edbc1cf0caa
Create Date: 2023-04-19 07:55:00.375602

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "b317896e8655"
down_revision = "1edbc1cf0caa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions_user_role_type",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "permissions_entity_map",
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "user_permission_uuid",
            sqlalchemy_utils.types.uuid.UUIDType(),
            nullable=False,
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_permission_uuid"], ["permissions_user_role_type.uuid"], "permissions_entity_map_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.add_column(
        "user",
        sa.Column("permissions_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    )
    op.create_foreign_key(None, "user", "permissions_entity_map", ["permissions_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "permissions_uuid")
    op.drop_table("permissions_entity_map")
    op.drop_table("permissions_user_role_type")
    # ### end Alembic commands ###
