"""Various data integrity improvements

Revision ID: bba4b4b01adf
Revises: 42cfca69a34d
Create Date: 2023-05-04 14:36:23.899823

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "bba4b4b01adf"
down_revision = "42cfca69a34d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "platform",
        "is_group",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "platform",
        "active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        nullable=True,
    )
    op.alter_column(
        "platform",
        "active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "platform",
        "is_group",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    # ### end Alembic commands ###
