"""entity and user uniqueness

Revision ID: bc561917bc69
Revises: 740cfe7ffd18
Create Date: 2024-08-22 16:10:15.237024

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "bc561917bc69"
down_revision = "740cfe7ffd18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_entity_entitlement_entity_uuid", "entity_entitlement", ["entity_uuid"])
    op.create_unique_constraint("unique_entitlement_user_uuid", "entitlement", ["user_uuid"])
    op.create_unique_constraint("unique_entitlement_usage_user_uuid", "entitlement_usage", ["user_uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_entity_entitlement_entity_uuid", "entity_entitlement")
    op.drop_constraint("unique_entitlement_user_uuid", "entitlement")
    op.drop_constraint("unique_entitlement_usage_user_uuid", "entitlement_usage")
    # ### end Alembic commands ###
