"""add endpointHeaders to ApiSource

Revision ID: c08bd0a7bafa
Revises: 8457325b0f24
Create Date: 2024-08-01 14:10:48.196237

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c08bd0a7bafa"
down_revision = "8457325b0f24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_source", sa.Column("endpointHeaders", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_source", "endpointHeaders")
    # ### end Alembic commands ###
