"""populate invite_your_colleagues

Revision ID: c23b912d4f38
Revises: 77ae861c5ac1
Create Date: 2024-09-17 18:11:21.117505

"""

import sqlalchemy as sa

from alembic import op
from api.models.tier_models import DataBundle  # type: ignore

# revision identifiers, used by Alembic.
revision = "c23b912d4f38"
down_revision = "77ae861c5ac1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.update(DataBundle)
        .where(DataBundle.bundle_name == "Default")
        .values(invite_your_colleagues=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
