"""organization name in developer onboarding

Revision ID: c2b83acdba36
Revises: ae65c3641b17
Create Date: 2024-08-26 10:14:42.932892

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c2b83acdba36"
down_revision = "ae65c3641b17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("developer_onboarding", sa.Column("organization_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("developer_onboarding", "organization_name")
    # ### end Alembic commands ###
