"""Added webhook fields

Revision ID: c49a1bc108d4
Revises: d7c84dd5d85d
Create Date: 2022-08-30 08:35:00.800504

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c49a1bc108d4"
down_revision = "d7c84dd5d85d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("webhook", sa.Column("name", sa.Text(), nullable=True))
    op.add_column("webhook", sa.Column("url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook", "url")
    op.drop_column("webhook", "name")
    # ### end Alembic commands ###
