"""Added new user info fields

Revision ID: c619a792d8d8
Revises: 3faba90206e7
Create Date: 2022-12-19 09:23:32.105388

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c619a792d8d8"
down_revision = "3faba90206e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("primary_usage", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("company_type", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("company_size", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("job_role", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "job_role")
    op.drop_column("user", "company_size")
    op.drop_column("user", "company_type")
    op.drop_column("user", "primary_usage")
    # ### end Alembic commands ###
