"""Add datakey to single widgets

Revision ID: c76a62849fae
Revises: 630413d79906
Create Date: 2024-06-18 10:28:03.847900

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c76a62849fae"
down_revision = "630413d79906"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("single_widget", sa.Column("data_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("single_widget", "data_key")
    # ### end Alembic commands ###
