"""Tauri type

Revision ID: c78bb503304f
Revises: b098ccf00935
Create Date: 2024-01-02 07:54:31.762367

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c78bb503304f"
down_revision = "b098ccf00935"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tauribuild", sa.Column("tauri_type", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tauribuild", "tauri_type")
    # ### end Alembic commands ###
