"""Added email to invite

Revision ID: c8077a00b236
Revises: 026bdc3ded4d
Create Date: 2023-11-21 07:39:26.213833

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c8077a00b236"
down_revision = "026bdc3ded4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_pro_invite",
        sa.Column("email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    )
    op.create_unique_constraint("user_pro_unqiue_email", "user_pro_invite", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_pro_unqiue_email", "user_pro_invite", type_="unique")
    op.drop_column("user_pro_invite", "email")
    # ### end Alembic commands ###
