"""tauri log

Revision ID: c85675379019
Revises: ab22ae76eda6
Create Date: 2023-02-21 14:12:50.557881

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "c85675379019"
down_revision = "ab22ae76eda6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tauri_log",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("log_type", sa.String(length=200), nullable=False),
        sa.Column("identifier", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_unique_constraint("identifier_date_unqiue", "tauri_log", ["identifier", "date", "log_type"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tauri_log")
    # ### end Alembic commands ###
