"""add email to reconciliation

Revision ID: ccfdf08df4d1
Revises: 215847288e23
Create Date: 2022-10-06 08:28:43.998912

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "ccfdf08df4d1"
down_revision = "215847288e23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reconciliation", sa.Column("email", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reconciliation", "email")
    # ### end Alembic commands ###
