"""unique widget id

Revision ID: cef1604d8a50
Revises: 6bfc3dd05897
Create Date: 2024-09-05 16:31:04.873562

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "cef1604d8a50"
down_revision = "6bfc3dd05897"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    op.drop_constraint("widget_metadata_ibfk_1", "widget_metadata", type_="foreignkey")
    if dialect == "mysql":
        op.drop_index("uix_user_name_type", table_name="widget_metadata")
    elif dialect == "postgresql":
        op.drop_constraint("uix_user_name_type", "widget_metadata", type_="unique")

    op.create_index(
        "ix_user_name_type",
        "widget_metadata",
        ["user_uuid", "name", "widget_type"],
        unique=False,
    )
    op.create_unique_constraint("u_widget_id", "widget_metadata", ["widget_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("u_widget_id", "widget_metadata", type_="unique")
    op.drop_index("ix_user_name_type", table_name="widget_metadata")
    op.create_index(
        "uix_user_name_type",
        "widget_metadata",
        ["user_uuid", "name", "widget_type"],
        unique=True,
    )
    # ### end Alembic commands ###
