"""User email newsletter

Revision ID: cf33521a47a5
Revises: b317896e8655
Create Date: 2023-04-27 10:33:59.770726

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "cf33521a47a5"
down_revision = "b317896e8655"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email_newsletter", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_newsletter")
    # ### end Alembic commands ###
