"""ip location

Revision ID: d7164fccbdb5
Revises: 52fbf9c6fb7a
Create Date: 2022-06-10 15:16:04.544529

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "d7164fccbdb5"
down_revision = "52fbf9c6fb7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("login", sa.Column("region", sa.String(length=100), nullable=True))
    op.add_column("login", sa.Column("region_iso_code", sa.String(length=100), nullable=True))
    op.add_column("login", sa.Column("postal_code", sa.String(length=10), nullable=True))
    op.add_column("login", sa.Column("country", sa.String(length=100), nullable=True))
    op.add_column("login", sa.Column("country_code", sa.String(length=10), nullable=True))
    op.add_column("login", sa.Column("continent", sa.String(length=100), nullable=True))
    op.add_column("login", sa.Column("continent_code", sa.String(length=10), nullable=True))
    op.add_column("login", sa.Column("timezone_name", sa.String(length=100), nullable=True))
    op.add_column("login", sa.Column("timezone_abbrev", sa.String(length=10), nullable=True))
    op.add_column("login", sa.Column("connection_type", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("login", "connection_type")
    op.drop_column("login", "timezone_abbrev")
    op.drop_column("login", "timezone_name")
    op.drop_column("login", "continent_code")
    op.drop_column("login", "continent")
    op.drop_column("login", "country_code")
    op.drop_column("login", "country")
    op.drop_column("login", "postal_code")
    op.drop_column("login", "region_iso_code")
    op.drop_column("login", "region")
    op.drop_column("login", "city")
    # ### end Alembic commands ###
