"""Add total referral to user

Revision ID: d7c84dd5d85d
Revises: 38aef2d3ba48
Create Date: 2022-07-27 09:35:37.407970

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "d7c84dd5d85d"
down_revision = "38aef2d3ba48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("total_referrals", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "total_referrals")
    # ### end Alembic commands ###
