"""rename column organization

Revision ID: dc4f90ea9151
Revises: 86e944acc97c
Create Date: 2024-08-05 10:30:23.277874

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "dc4f90ea9151"
down_revision = "86e944acc97c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("developer_onboarding", sa.Column("organization", sa.Text(), nullable=True))
    op.drop_column("developer_onboarding", "organization_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "developer_onboarding",
        sa.Column("organization_type", sa.TEXT(), nullable=True),
    )
    op.drop_column("developer_onboarding", "organization")
    # ### end Alembic commands ###
