"""allowsnullsinplan


Revision ID: dee2a485b94b
Revises: 89cc366275d7
Create Date: 2022-06-07 21:36:24.389423

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "dee2a485b94b"
down_revision = "89cc366275d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("plan", "external_name", existing_type=sa.VARCHAR(length=128), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("plan", "external_name", existing_type=sa.VARCHAR(length=128), nullable=False)
    # ### end Alembic commands ###
