"""Added hubspot_id

Revision ID: df05854a85e9
Revises: 5b606deef737
Create Date: 2023-10-05 14:43:42.648499

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "df05854a85e9"
down_revision = "5b606deef737"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hubspot_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hubspot_id")
    # ### end Alembic commands ###
