"""Add file widget

Revision ID: e3bb43413f6c
Revises: 4e25caffe677
Create Date: 2024-05-24 16:28:45.899759

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op  # type: ignore
from api.models.model_helpers import AwareDateTime

# revision identifiers, used by Alembic.
revision = "e3bb43413f6c"
down_revision = "4e25caffe677"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_widget",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("extension", sa.Text(), nullable=False),
        sa.Column("original_file_name", sa.Text(), nullable=True),
        sa.Column("data_key", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("sub_category", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.alter_column("single_widget", "description", existing_type=sa.Text(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_widget")
    op.alter_column("single_widget", "description", existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###
