"""Add info to entity table

Revision ID: e3e2c3066379
Revises: 468c3559b836
Create Date: 2023-09-11 17:34:20.743925

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "e3e2c3066379"
down_revision = "468c3559b836"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("email", sa.String(length=200), nullable=True))
    op.add_column("entity", sa.Column("company_type", sa.String(length=20), nullable=True))
    op.add_column("entity", sa.Column("organization_size", sa.String(length=20), nullable=True))
    op.add_column("entity", sa.Column("aum", sa.Integer(), nullable=True))
    op.add_column("entity", sa.Column("country", sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "country")
    op.drop_column("entity", "aum")
    op.drop_column("entity", "organization_size")
    op.drop_column("entity", "company_type")
    op.drop_column("entity", "email")
    # ### end Alembic commands ###
