"""Add the zero to hero info

Revision ID: e6f7e6f2f1b0
Revises: 1b27503b4057
Create Date: 2024-03-21 15:21:38.383981

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import ProZeroToHeroType

# revision identifiers, used by Alembic.
revision = "e6f7e6f2f1b0"
down_revision = "1b27503b4057"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("pro_zero_to_hero", ProZeroToHeroType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pro_zero_to_hero")
    # ### end Alembic commands ###
