"""Remove email tracking in user

Revision ID: e7732d82eb9d
Revises: df05854a85e9
Create Date: 2023-10-10 16:10:16.460889

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "e7732d82eb9d"
down_revision = "df05854a85e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_newsletter")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "email_newsletter",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
