"""Key value pair

Revision ID: e89d0a626693
Revises: 76f58b355a79
Create Date: 2023-06-09 07:39:18.413000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql, postgresql

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "e89d0a626693"
down_revision = "76f58b355a79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "info_store",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column(
            "value",
            sa.Text().with_variant(postgresql.TEXT(), "postgresql").with_variant(mysql.LONGTEXT(), "mysql"),
            nullable=True,
        ),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("info_store")
    # ### end Alembic commands ###
