"""Added user info

Revision ID: eb9e51e4c4d0
Revises: 0ffea848800c
Create Date: 2023-03-09 11:51:44.419390

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "eb9e51e4c4d0"
down_revision = "0ffea848800c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("asset_classes", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("organization_type", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("organization_size", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("organization_country", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("organization_name", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("market_focus", sa.Text(), nullable=True))
    op.add_column(
        "user", sa.Column("investing_for_client", sa.Boolean(), nullable=False)
    )
    op.add_column("user", sa.Column("wants_contacted", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("university", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("role", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("fund_club_intro", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("university_intro", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("how_we_help", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("investment_approach", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("hours_per_week", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("finance_market", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("discusses", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("investment_community", sa.Text(), nullable=True))
    op.drop_column("user", "company_type")
    op.drop_column("user", "company_size")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "company_size",
            sa.Text().with_variant(
                mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), "mysql"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "company_type",
            sa.Text().with_variant(
                mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), "mysql"
            ),
            nullable=True,
        ),
    )
    op.drop_column("user", "investment_community")
    op.drop_column("user", "discusses")
    op.drop_column("user", "finance_market")
    op.drop_column("user", "hours_per_week")
    op.drop_column("user", "investment_approach")
    op.drop_column("user", "how_we_help")
    op.drop_column("user", "university_intro")
    op.drop_column("user", "fund_club_intro")
    op.drop_column("user", "role")
    op.drop_column("user", "university")
    op.drop_column("user", "wants_contacted")
    op.drop_column("user", "investing_for_client")
    op.drop_column("user", "market_focus")
    op.drop_column("user", "organization_name")
    op.drop_column("user", "organization_country")
    op.drop_column("user", "organization_size")
    op.drop_column("user", "organization_type")
    op.drop_column("user", "asset_classes")
    # ### end Alembic commands ###
