"""Give entities a keys JSON

Revision ID: ebf7a561ea58
Revises: c8077a00b236
Create Date: 2023-11-22 16:35:48.006858

"""

import sqlalchemy as sa

from alembic import op  # type: ignore
from api.models.model_helpers import ProKeysType

# revision identifiers, used by Alembic.
revision = "ebf7a561ea58"
down_revision = "c8077a00b236"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("api_keys", ProKeysType(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "api_keys")
    # ### end Alembic commands ###
