"""Add a username

Revision ID: f098e52ff468
Revises: bba4b4b01adf
Create Date: 2023-05-16 11:39:41.133632

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "f098e52ff468"
down_revision = "bba4b4b01adf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
