"""allow copilto_table as widget_type

Revision ID: f1317bfd4f67
Revises: 9ac3a287ad86
Create Date: 2024-10-03 15:16:33.539344

"""

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "f1317bfd4f67"
down_revision = "9ac3a287ad86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("widget_type_check", "widget_metadata", type_="check")
    op.create_check_constraint(
        "widget_type_check",
        "widget_metadata",
        "widget_type IN ('iframe', 'rss_viewer', 'rich_note', 'copilot_table')",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("widget_type_check", "widget_metadata", type_="check")
    op.create_check_constraint(
        "widget_type_check",
        "widget_metadata",
        "widget_type IN ('iframe', 'rss_viewer', 'rich_note')",
    )
    # ### end Alembic commands ###
