"""Add emails columns to feature

Revision ID: f5b7610a09f2
Revises: 8ec5bee317b9
Create Date: 2022-11-08 16:10:00.414931

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "f5b7610a09f2"
down_revision = "8ec5bee317b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feature", sa.Column("emails", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature", "emails")
    # ### end Alembic commands ###
