"""Add pro feedback columns

Revision ID: f68cbfa1d80d
Revises: ebf7a561ea58
Create Date: 2023-11-29 14:45:39.812914

"""

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "f68cbfa1d80d"
down_revision = "ebf7a561ea58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("feedback_like", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("feedback_improve", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("feedback_to_pay", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "feedback_to_pay")
    op.drop_column("user", "feedback_improve")
    op.drop_column("user", "feedback_like")
    # ### end Alembic commands ###
