"""renamed table to copilot_chats

Revision ID: fc3f76a24f2e
Revises: 569090101767
Create Date: 2024-07-09 17:58:33.026069

"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op
from api.models.model_helpers import DATETIME, AwareDateTime, GzipJsonType, get_mediumblob  # type: ignore

# revision identifiers, used by Alembic.
revision = "fc3f76a24f2e"
down_revision = "569090101767"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "copilot_chats",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("chats", GzipJsonType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", AwareDateTime(), nullable=True),
        sa.Column("updated_date", AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.drop_table("copilot_chat")
    # ### end Alembic commands ###


def downgrade():
    dialect = op.get_bind().dialect.name
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "copilot_chat",
        sa.Column("user_uuid", sa.BINARY(length=16), nullable=False),
        sa.Column("uuid", sa.BINARY(length=16), nullable=False),
        sa.Column("created_date", DATETIME(), nullable=True),
        sa.Column("updated_date", DATETIME(), nullable=True),
        sa.Column("chats", get_mediumblob(dialect), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name="copilot_chat_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("uuid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("copilot_chats")
    # ### end Alembic commands ###
