import { describe, expect, it } from "vitest";
import { buildIframeWidget } from "~/components/Widgets/custom/buildIframeWidget";

describe("buildIframeWidget", () => {
  it("builds an iframe custom-widget payload from a url", () => {
    const widget = buildIframeWidget("https://example.com/report", "Copilot");

    expect(widget).toMatchObject({
      widgetId: "iframe",
      type: "custom",
      name: "example.com",
      description: "Iframe for https://example.com/report. Generated by Copilot",
      storage: { html: "https://example.com/report" },
    });
    expect(widget.id).toEqual(expect.any(String));
  });

  it("falls back to a generic name for an unparseable url", () => {
    expect(buildIframeWidget("not a url", "Copilot").name).toBe("Website");
  });

  it("includes innerTab only when provided", () => {
    expect(buildIframeWidget("https://example.com", "Copilot", "tab-1").innerTab).toBe(
      "tab-1",
    );
    expect(buildIframeWidget("https://example.com", "Copilot")).not.toHaveProperty(
      "innerTab",
    );
  });
});
