"""baseline - squashed schema (frozen)

All migrations prior to the squash were collapsed into this single baseline.
The schema below is an explicit, frozen snapshot of the models as they
existed at squash time. It is intentionally NOT generated from live model
metadata (``Base.metadata.create_all``): a live baseline already contains
every table/column added by later migrations, which makes any post-baseline
migration crash with "already exists" on fresh databases.

Schema changes made after the squash belong in normal migrations
(0003 onwards) and must NOT be edited into this file.

For EXISTING pre-squash databases (MySQL/PostgreSQL):
    The guard below detects the populated schema and skips this migration.

For NEW databases (any dialect including SQLite):
    ``alembic upgrade head`` replays this baseline plus all later migrations.

Revision ID: 0001
Revises: 7f2e1b4314ef
Create Date: 2026-02-23

"""

import sqlalchemy as sa
import sqlalchemy_utils

import api.models.model_helpers
from alembic import op  # type: ignore

revision = "0001"
down_revision = "7f2e1b4314ef"
branch_labels = None
depends_on = None


def upgrade():  # noqa: PLR0915 - frozen baseline creates the full schema
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if "user" in existing_tables:
        # Existing pre-squash database - the old migration chain already
        # created everything. Nothing to do.
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_bundle",
        sa.Column("bundle_name", sa.String(length=50), nullable=False),
        sa.Column(
            "except_widgets", api.models.model_helpers.JSONType(), nullable=False
        ),
        sa.Column(
            "except_dashboard_templates",
            api.models.model_helpers.JSONType(),
            nullable=False,
        ),
        sa.Column(
            "except_team_collaboration",
            api.models.model_helpers.JSONType(),
            nullable=True,
        ),
        sa.Column("excel_add_in", sa.Boolean(), nullable=False),
        sa.Column("data_export", sa.Boolean(), nullable=False),
        sa.Column("providers", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column(
            "dashboards_at_launch", api.models.model_helpers.JSONType(), nullable=True
        ),
        sa.Column("my_dashboards", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column("invite_your_colleagues", sa.Boolean(), nullable=False),
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
        sa.Column("allow_custom_backends", sa.Boolean(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("bundle_name"),
    )
    op.create_table(
        "entity_type",
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("permission_hierarchy", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "feedback",
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("emoji", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "log",
        sa.Column("request", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "tier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("has_trial", sa.Boolean(), nullable=False),
        sa.Column("trial_duration_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "default_tier",
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
        sa.Column("share_widgets", sa.String(length=20), nullable=True),
        sa.Column("data_bundle", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_data", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_copilot", sa.Boolean(), nullable=True),
        sa.Column("admin_access", sa.Boolean(), nullable=True),
        sa.Column("support", sa.Boolean(), nullable=True),
        sa.Column("excel_add_in", sa.Boolean(), nullable=True),
        sa.Column("data_add_ons_redistribution", sa.Boolean(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.CheckConstraint(
            "share_widgets IN ('public', 'private')",
            name="check_share_widgets_values_tier_defaults",
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"], ["tier.id"], name=op.f("fk_default_tier_tier_id_tier")
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "entity",
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column(
            "entity_type_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("company_type", sa.String(length=20), nullable=True),
        sa.Column("organization_size", sa.String(length=20), nullable=True),
        sa.Column("aum", sa.BigInteger(), nullable=True),
        sa.Column("country", sa.String(length=60), nullable=True),
        sa.Column("require_authenticator", sa.Boolean(), nullable=False),
        sa.Column("api_keys", api.models.model_helpers.ProKeysType(), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column(
            "expiration_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column("stripe_id", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["entity_type_uuid"],
            ["entity_type.uuid"],
            name=op.f("fk_entity_entity_type_uuid_entity_type"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("entity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_entity_type_uuid"), ["entity_type_uuid"], unique=False
        )

    op.create_table(
        "entity_entitlement",
        sa.Column(
            "entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
        sa.Column("share_widgets", sa.String(length=20), nullable=True),
        sa.Column("bring_your_own_data", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_copilot", sa.Boolean(), nullable=True),
        sa.Column("admin_access", sa.Boolean(), nullable=True),
        sa.Column("support", sa.Boolean(), nullable=True),
        sa.Column("excel_add_in", sa.Boolean(), nullable=True),
        sa.Column("data_add_ons_redistribution", sa.Boolean(), nullable=True),
        sa.Column("allow_custom_backends", sa.Boolean(), nullable=True),
        sa.Column(
            "data_bundle_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.CheckConstraint(
            "share_widgets IN ('public', 'private')",
            name="check_share_widgets_values_entity_entitlements",
        ),
        sa.ForeignKeyConstraint(
            ["data_bundle_uuid"],
            ["data_bundle.uuid"],
            name=op.f("fk_entity_entitlement_data_bundle_uuid_data_bundle"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_entity_entitlement_entity_uuid_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"], ["tier.id"], name=op.f("fk_entity_entitlement_tier_id_tier")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("entity_entitlement", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_entitlement_entity_uuid"),
            ["entity_uuid"],
            unique=True,
        )

    op.create_table(
        "entity_relationship",
        sa.Column(
            "parent_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("child_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "supreme_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["child_uuid"],
            ["entity.uuid"],
            name=op.f("fk_entity_relationship_child_uuid_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_uuid"],
            ["entity.uuid"],
            name=op.f("fk_entity_relationship_parent_uuid_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["supreme_uuid"],
            ["entity.uuid"],
            name=op.f("fk_entity_relationship_supreme_uuid_entity"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("entity_relationship", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_relationship_child_uuid"),
            ["child_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_entity_relationship_parent_uuid"),
            ["parent_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_entity_relationship_supreme_uuid"),
            ["supreme_uuid"],
            unique=False,
        )

    op.create_table(
        "entity_theme_settings",
        sa.Column(
            "entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("settings", api.models.model_helpers.GzipJsonType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_entity_theme_settings_entity_uuid_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("entity_theme_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_theme_settings_entity_uuid"),
            ["entity_uuid"],
            unique=False,
        )

    op.create_table(
        "permissions_entity_map",
        sa.Column(
            "entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "entitlements",
            api.models.model_helpers.ProEntitlementsType(),
            nullable=True,
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_permissions_entity_map_entity_uuid_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("permissions_entity_map", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_permissions_entity_map_entity_uuid"),
            ["entity_uuid"],
            unique=False,
        )

    op.create_table(
        "role",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "deleted_at",
            api.models.model_helpers.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_role_entity_uuid_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint(
            "entity_uuid", "name", "deleted_at", name="uix_role_entity_name_deleted_at"
        ),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_role_entity_uuid"), ["entity_uuid"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column(
            "clean_email",
            sqlalchemy_utils.types.email.EmailType(length=255),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column(
            "password",
            api.models.model_helpers.PasswordType(length=128),
            nullable=False,
        ),
        sa.Column("totp_secret", sa.String(length=32), nullable=True),
        sa.Column("totp_active", sa.Boolean(), nullable=False),
        sa.Column("two_factor_auth", sa.Boolean(), nullable=False),
        sa.Column("temporary_password", sa.Boolean(), nullable=True),
        sa.Column("auth_token", sa.Text(), nullable=True),
        sa.Column(
            "pro_entitlements",
            api.models.model_helpers.ProEntitlementsType(),
            nullable=True,
        ),
        sa.Column(
            "pro_display_settings",
            api.models.model_helpers.ProDisplaySettingsType(),
            nullable=True,
        ),
        sa.Column(
            "pro_zero_to_hero",
            api.models.model_helpers.ProZeroToHeroType(),
            nullable=True,
        ),
        sa.Column("primary_usage", sa.Text(), nullable=True),
        sa.Column("wants_contacted", sa.Boolean(), nullable=True),
        sa.Column("referred_by", sa.String(length=100), nullable=True),
        sa.Column("referred_by_sent", sa.Boolean(), nullable=True),
        sa.Column("referral_code", sa.String(length=100), nullable=False),
        sa.Column("total_referrals", sa.Integer(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("has_profile_url", sa.Boolean(), nullable=True),
        sa.Column(
            "permissions_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column("billing_active", sa.Boolean(), nullable=True),
        sa.Column("accepted_pro_tos", sa.Boolean(), nullable=True),
        sa.Column("pro_trial_granted", sa.Boolean(), nullable=True),
        sa.Column(
            "pro_trial_granted_date",
            api.models.model_helpers.AwareDateTime(),
            nullable=True,
        ),
        sa.Column(
            "pro_trial_end", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column("pro_trial_extension", sa.Boolean(), nullable=True),
        sa.Column("pro_trial_renewals", sa.Integer(), nullable=True),
        sa.Column("pro_start", api.models.model_helpers.AwareDateTime(), nullable=True),
        sa.Column("latest_version", sa.Text(), nullable=True),
        sa.Column("pro_inactivity_email_sent", sa.Boolean(), nullable=True),
        sa.Column("welcome_screen", sa.Boolean(), nullable=True),
        sa.Column("hear_about_us", sa.Text(), nullable=True),
        sa.Column("stripe_id", sa.String(length=50), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["permissions_uuid"],
            ["permissions_entity_map.uuid"],
            name=op.f("fk_user_permissions_uuid_permissions_entity_map"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("referral_code"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_permissions_uuid"), ["permissions_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_stripe_id"), ["stripe_id"], unique=False
        )

    op.create_table(
        "audit_entity_roles_permissions",
        sa.Column(
            "entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column(
            "resource_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "performed_by_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("details", api.models.model_helpers.GzipJsonType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_audit_entity_roles_permissions_entity_uuid_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_uuid"],
            ["user.uuid"],
            name=op.f("fk_audit_entity_roles_permissions_performed_by_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["role.uuid"],
            name=op.f("fk_audit_entity_roles_permissions_role_uuid_role"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table(
        "audit_entity_roles_permissions", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_entity_roles_permissions_entity_uuid"),
            ["entity_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_entity_roles_permissions_performed_by_uuid"),
            ["performed_by_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_entity_roles_permissions_resource_uuid"),
            ["resource_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_entity_roles_permissions_role_uuid"),
            ["role_uuid"],
            unique=False,
        )

    op.create_table(
        "copilot_chat",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "content", api.models.model_helpers.GzipJsonLongType(), nullable=True
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_copilot_chat_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("copilot_chat", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_copilot_chat_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "copilot_chats",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("chats", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_copilot_chats_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid"),
    )
    op.create_table(
        "custom_copilot",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("headers", api.models.model_helpers.EncryptedType(), nullable=True),
        sa.Column("copilots", api.models.model_helpers.EncryptedType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_custom_copilot_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "url", name="uix_user_url_custom_copilot"),
    )
    with op.batch_alter_table("custom_copilot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_custom_copilot_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "dashboard_item",
        sa.Column(
            "creator_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("owner_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("entity_share", sa.Boolean(), nullable=False),
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column(
            "content", api.models.model_helpers.GzipJsonLongType(), nullable=True
        ),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["creator_uuid"],
            ["user.uuid"],
            name=op.f("fk_dashboard_item_creator_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_dashboard_item_entity_uuid_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_uuid"],
            ["user.uuid"],
            name=op.f("fk_dashboard_item_owner_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("dashboard_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dashboard_item_creator_uuid"), ["creator_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dashboard_item_entity_share"), ["entity_share"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dashboard_item_entity_uuid"), ["entity_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dashboard_item_is_shared"), ["is_shared"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dashboard_item_owner_uuid"), ["owner_uuid"], unique=False
        )

    op.create_table(
        "developer_onboarding",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("primary_usage", sa.Text(), nullable=True),
        sa.Column("organization", sa.Text(), nullable=True),
        sa.Column("organization_name", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("programming_experience", sa.Text(), nullable=True),
        sa.Column("data_types", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column("other_data_types", sa.Text(), nullable=True),
        sa.Column("skip_onboarding", sa.Boolean(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_developer_onboarding_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("developer_onboarding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_developer_onboarding_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "enabled_widget_bundles",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "enabled_bundles",
            sqlalchemy_utils.types.scalar_list.ScalarListType(),
            nullable=False,
        ),
        sa.Column(
            "disabled_widgets",
            sqlalchemy_utils.types.scalar_list.ScalarListType(),
            nullable=True,
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_enabled_widget_bundles_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid"),
    )
    op.create_table(
        "entitlement",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("number_copilot_calls_day", sa.Integer(), nullable=True),
        sa.Column("total_file_upload_size_gb", sa.Integer(), nullable=True),
        sa.Column("share_widgets", sa.String(length=20), nullable=True),
        sa.Column("bring_your_own_data", sa.Boolean(), nullable=True),
        sa.Column("bring_your_own_copilot", sa.Boolean(), nullable=True),
        sa.Column("admin_access", sa.Boolean(), nullable=True),
        sa.Column("support", sa.Boolean(), nullable=True),
        sa.Column("excel_add_in", sa.Boolean(), nullable=True),
        sa.Column("data_add_ons_redistribution", sa.Boolean(), nullable=True),
        sa.Column("allow_custom_backends", sa.Boolean(), nullable=True),
        sa.Column(
            "data_bundle_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.CheckConstraint(
            "share_widgets IN ('public', 'private')",
            name="check_share_widgets_values_entitlements",
        ),
        sa.ForeignKeyConstraint(
            ["data_bundle_uuid"],
            ["data_bundle.uuid"],
            name=op.f("fk_entitlement_data_bundle_uuid_data_bundle"),
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"], ["tier.id"], name=op.f("fk_entitlement_tier_id_tier")
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_entitlement_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("entitlement", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entitlement_user_uuid"), ["user_uuid"], unique=True
        )

    op.create_table(
        "entitlement_usage",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("number_copilot_calls_day_count", sa.Integer(), nullable=False),
        sa.Column("total_file_upload_size_gb_count", sa.Float(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_entitlement_usage_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("entitlement_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entitlement_usage_user_uuid"), ["user_uuid"], unique=True
        )

    op.create_table(
        "file_widget",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("url", api.models.model_helpers.HttpUrlType(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("extension", sa.Text(), nullable=False),
        sa.Column("original_file_name", sa.Text(), nullable=True),
        sa.Column("data_key", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("sub_category", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_file_widget_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("file_widget", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_widget_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "login",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column(
            "ip_address",
            sqlalchemy_utils.types.ip_address.IPAddressType(length=50),
            nullable=True,
        ),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("region_iso_code", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("country_code", sa.String(length=10), nullable=True),
        sa.Column("continent", sa.String(length=100), nullable=True),
        sa.Column("continent_code", sa.String(length=10), nullable=True),
        sa.Column("timezone_name", sa.String(length=100), nullable=True),
        sa.Column("timezone_abbrev", sa.String(length=10), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("connection_type", sa.String(length=100), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_login_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("login", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "mcp_servers",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("servers", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_mcp_servers_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("mcp_servers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mcp_servers_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "permissions_invite",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "permissions_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column(
            "expiration_date", api.models.model_helpers.AwareDateTime(), nullable=False
        ),
        sa.Column(
            "shared_dashboards", api.models.model_helpers.JSONType(), nullable=True
        ),
        sa.Column("shared_apps", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["permissions_uuid"],
            ["permissions_entity_map.uuid"],
            name=op.f("fk_permissions_invite_permissions_uuid_permissions_entity_map"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_permissions_invite_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("permissions_invite", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_permissions_invite_permissions_uuid"),
            ["permissions_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_permissions_invite_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "session",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("api_token", sa.String(length=300), nullable=True),
        sa.Column(
            "expiration_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column("pro", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_session_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "single_widget",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("grid_data", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column("data", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column(
            "endpoint_headers", api.models.model_helpers.JSONType(), nullable=True
        ),
        sa.Column(
            "source", sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True
        ),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("sub_category", sa.Text(), nullable=True),
        sa.Column("data_key", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_single_widget_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("single_widget", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_single_widget_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "trading_view",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "charts_state", api.models.model_helpers.GzipJsonType(), nullable=False
        ),
        sa.Column("settings", api.models.model_helpers.GzipJsonType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_trading_view_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid"),
    )
    op.create_table(
        "user_app",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "content", api.models.model_helpers.GzipJsonLongType(), nullable=True
        ),
        sa.Column("is_shared", sa.Boolean(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_user_app_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("user_app", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_app_is_shared"), ["is_shared"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_app_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "user_pro_invite",
        sa.Column(
            "inviting_user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column(
            "permissions_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column("data", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column(
            "shared_dashboards", api.models.model_helpers.JSONType(), nullable=True
        ),
        sa.Column("shared_apps", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["inviting_user_uuid"],
            ["user.uuid"],
            name=op.f("fk_user_pro_invite_inviting_user_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["permissions_uuid"],
            ["permissions_entity_map.uuid"],
            name=op.f("fk_user_pro_invite_permissions_uuid_permissions_entity_map"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("user_pro_invite", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_pro_invite_inviting_user_uuid"),
            ["inviting_user_uuid"],
            unique=False,
        )

    op.create_table(
        "user_prompts",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("prompt", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_user_prompts_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("user_prompts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_prompts_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "user_role",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["role.uuid"],
            name=op.f("fk_user_role_role_uuid_role"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_user_role_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("user_role", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_role_role_uuid"), ["role_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_role_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "user_skills",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", api.models.model_helpers.GzipStringType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_user_skills_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "slug", name="uq_user_skills_user_uuid_slug"),
    )
    with op.batch_alter_table("user_skills", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_skills_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "vendor",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=512), nullable=True),
        sa.Column("documentation_url", sa.String(length=512), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("support_email", sa.String(length=255), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["owner_uuid"],
            ["user.uuid"],
            name=op.f("fk_vendor_owner_uuid_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("vendor", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vendor_owner_uuid"), ["owner_uuid"], unique=False
        )

    op.create_table(
        "widget_metadata",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("sub_category", sa.String(length=50), nullable=False),
        sa.Column("widget_type", sa.String(length=50), nullable=False),
        sa.Column("storage", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column(
            "widget_config", api.models.model_helpers.GzipJsonType(), nullable=True
        ),
        sa.Column("widget_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_widget_metadata_user_uuid_user")
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("widget_id"),
    )
    with op.batch_alter_table("widget_metadata", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_name_type", ["user_uuid", "name", "widget_type"], unique=False
        )

    op.create_table(
        "dashboard_save",
        sa.Column(
            "dashboard_item_uuid",
            sqlalchemy_utils.types.uuid.UUIDType(),
            nullable=False,
        ),
        sa.Column("content", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column("created_date", api.models.model_helpers.DATETIME(), nullable=True),
        sa.Column("updated_date", api.models.model_helpers.DATETIME(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dashboard_item_uuid"],
            ["dashboard_item.uuid"],
            name=op.f("fk_dashboard_save_dashboard_item_uuid_dashboard_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("dashboard_save", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dashboard_save_dashboard_item_uuid"),
            ["dashboard_item_uuid"],
            unique=False,
        )

    op.create_table(
        "dashboard_share",
        sa.Column(
            "dashboard_item_uuid",
            sqlalchemy_utils.types.uuid.UUIDType(),
            nullable=False,
        ),
        sa.Column(
            "shared_user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "permissions",
            sa.Enum("view", "comment", "edit", name="permissionenum"),
            nullable=False,
        ),
        sa.Column("viewed", sa.Boolean(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["dashboard_item_uuid"],
            ["dashboard_item.uuid"],
            name=op.f("fk_dashboard_share_dashboard_item_uuid_dashboard_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shared_user_uuid"],
            ["user.uuid"],
            name=op.f("fk_dashboard_share_shared_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("dashboard_share", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dashboard_share_active"), ["active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dashboard_share_dashboard_item_uuid"),
            ["dashboard_item_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_dashboard_share_shared_user_uuid"),
            ["shared_user_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_dashboard_share_viewed"), ["viewed"], unique=False
        )

    op.create_table(
        "role_file",
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("file_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("access", sa.String(length=100), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["file_uuid"],
            ["file_widget.uuid"],
            name=op.f("fk_role_file_file_uuid_file_widget"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["role.uuid"],
            name=op.f("fk_role_file_role_uuid_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("role_file", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_role_file_file_uuid"), ["file_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_role_file_role_uuid"), ["role_uuid"], unique=False
        )

    op.create_table(
        "role_prompt",
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "prompt_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("access", sa.String(length=100), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["prompt_uuid"],
            ["user_prompts.uuid"],
            name=op.f("fk_role_prompt_prompt_uuid_user_prompts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["role.uuid"],
            name=op.f("fk_role_prompt_role_uuid_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("role_prompt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_role_prompt_prompt_uuid"), ["prompt_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_role_prompt_role_uuid"), ["role_uuid"], unique=False
        )

    op.create_table(
        "stored_file",
        sa.Column(
            "creater_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "file_widget_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column("s3_file_name", sa.Text(), nullable=False),
        sa.Column("bucket", sa.Text(), nullable=False),
        sa.Column("extension", sa.Text(), nullable=False),
        sa.Column("original_file_name", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("is_entity_shared", sa.Boolean(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["creater_uuid"],
            ["user.uuid"],
            name=op.f("fk_stored_file_creater_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["file_widget_uuid"],
            ["file_widget.uuid"],
            name=op.f("fk_stored_file_file_widget_uuid_file_widget"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("stored_file", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stored_file_creater_uuid"), ["creater_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stored_file_file_widget_uuid"),
            ["file_widget_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stored_file_is_entity_shared"),
            ["is_entity_shared"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stored_file_is_global"), ["is_global"], unique=False
        )

    op.create_table(
        "stored_file_share",
        sa.Column(
            "dashboard_item_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column(
            "user_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column(
            "creater_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "shared_user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "stored_file_uuids",
            sqlalchemy_utils.types.scalar_list.ScalarListType(),
            nullable=False,
        ),
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["creater_uuid"],
            ["user.uuid"],
            name=op.f("fk_stored_file_share_creater_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["dashboard_item_uuid"],
            ["dashboard_item.uuid"],
            name=op.f("fk_stored_file_share_dashboard_item_uuid_dashboard_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_stored_file_share_entity_uuid_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["shared_user_uuid"],
            ["user.uuid"],
            name=op.f("fk_stored_file_share_shared_user_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["user_app_uuid"],
            ["user_app.uuid"],
            name=op.f("fk_stored_file_share_user_app_uuid_user_app"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("stored_file_share", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stored_file_share_creater_uuid"),
            ["creater_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stored_file_share_dashboard_item_uuid"),
            ["dashboard_item_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stored_file_share_entity_uuid"),
            ["entity_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stored_file_share_shared_user_uuid"),
            ["shared_user_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stored_file_share_user_app_uuid"),
            ["user_app_uuid"],
            unique=False,
        )

    op.create_table(
        "user_app_share",
        sa.Column(
            "user_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column(
            "shared_user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "permissions",
            sa.Enum("view", "comment", "edit", name="permissionenum"),
            nullable=False,
        ),
        sa.Column("viewed", sa.Boolean(), nullable=False),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["shared_user_uuid"],
            ["user.uuid"],
            name=op.f("fk_user_app_share_shared_user_uuid_user"),
        ),
        sa.ForeignKeyConstraint(
            ["user_app_uuid"],
            ["user_app.uuid"],
            name=op.f("fk_user_app_share_user_app_uuid_user_app"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("user_app_share", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_app_share_active"), ["active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_app_share_shared_user_uuid"),
            ["shared_user_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_app_share_user_app_uuid"),
            ["user_app_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_app_share_viewed"), ["viewed"], unique=False
        )

    op.create_table(
        "vendor_app",
        sa.Column(
            "vendor_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("owner_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("tagline", sa.String(length=255), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url_dark", sa.Text(), nullable=True),
        sa.Column("thumbnail_url_light", sa.Text(), nullable=True),
        sa.Column("screenshots", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column("api_key_url", sa.String(length=512), nullable=True),
        sa.Column("api_key_info_url", sa.String(length=512), nullable=True),
        sa.Column("more_information_url", sa.String(length=512), nullable=True),
        sa.Column("backend_base_url", sa.String(length=512), nullable=True),
        sa.Column("apps_json_url", sa.String(length=512), nullable=True),
        sa.Column("widgets_json_url", sa.String(length=512), nullable=True),
        sa.Column("is_built_in", sa.Boolean(), nullable=False),
        sa.Column("auth_type", api.models.model_helpers.JSONType(), nullable=False),
        sa.Column("auth_fields", api.models.model_helpers.JSONType(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "verified",
                "development",
                "published",
                "disabled",
                "removed",
                name="appstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "apps_json_cache", api.models.model_helpers.GzipJsonType(), nullable=True
        ),
        sa.Column(
            "widgets_json_cache", api.models.model_helpers.GzipJsonType(), nullable=True
        ),
        sa.Column("apps_json_version", sa.String(length=100), nullable=True),
        sa.Column("widgets_json_version", sa.String(length=100), nullable=True),
        sa.Column(
            "last_fetched_at", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column("last_fetch_status", sa.String(length=10), nullable=True),
        sa.Column("last_fetch_error", sa.Text(), nullable=True),
        sa.Column(
            "last_verified_at", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "parent_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["owner_uuid"],
            ["user.uuid"],
            name=op.f("fk_vendor_app_owner_uuid_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_app_uuid"],
            ["vendor_app.uuid"],
            name=op.f("fk_vendor_app_parent_app_uuid_vendor_app"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_uuid"],
            ["vendor.uuid"],
            name=op.f("fk_vendor_app_vendor_uuid_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint(
            "vendor_uuid", "name", "version", name="uq_vendor_app_name_version"
        ),
    )
    with op.batch_alter_table("vendor_app", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vendor_app_owner_uuid"), ["owner_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_vendor_app_parent_app_uuid"),
            ["parent_app_uuid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_vendor_app_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_vendor_app_vendor_status", ["vendor_uuid", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_vendor_app_vendor_uuid"), ["vendor_uuid"], unique=False
        )

    op.create_table(
        "api_source",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", api.models.model_helpers.HttpUrlType(), nullable=False),
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column(
            "endpointHeaders", api.models.model_helpers.EncryptedType(), nullable=True
        ),
        sa.Column("entity_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column(
            "vendor_app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.CheckConstraint(
            "user_uuid IS NOT NULL OR entity_uuid IS NOT NULL",
            name="check_user_or_entity_api_source",
        ),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
            name=op.f("fk_api_source_entity_uuid_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name=op.f("fk_api_source_user_uuid_user")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_app_uuid"],
            ["vendor_app.uuid"],
            name=op.f("fk_api_source_vendor_app_uuid_vendor_app"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("api_source", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_source_entity_uuid"), ["entity_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_api_source_user_uuid"), ["user_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_api_source_vendor_app_uuid"),
            ["vendor_app_uuid"],
            unique=False,
        )
        batch_op.create_index(
            "ix_user_entity_name_api_source",
            ["user_uuid", "entity_uuid", "name"],
            unique=False,
        )

    op.create_table(
        "rate_vendor_app",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review", sa.Text(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["app_uuid"],
            ["vendor_app.uuid"],
            name=op.f("fk_rate_vendor_app_app_uuid_vendor_app"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_rate_vendor_app_user_uuid_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "app_uuid", name="uq_user_app_rating"),
    )
    with op.batch_alter_table("rate_vendor_app", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rate_vendor_app_app_uuid"), ["app_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rate_vendor_app_user_uuid"), ["user_uuid"], unique=False
        )

    op.create_table(
        "user_app_subscription",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("app_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disconnected", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column(
            "subscribed_at", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "disconnected_at", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["app_uuid"],
            ["vendor_app.uuid"],
            name=op.f("fk_user_app_subscription_app_uuid_vendor_app"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_user_app_subscription_user_uuid_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid", "app_uuid", name="uq_user_app_subscription"),
    )
    with op.batch_alter_table("user_app_subscription", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_app_sub_user_status", ["user_uuid", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_app_subscription_app_uuid"), ["app_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_app_subscription_user_uuid"),
            ["user_uuid"],
            unique=False,
        )

    op.create_table(
        "role_backend",
        sa.Column("role_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "backend_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column("access", sa.String(length=100), nullable=False),
        sa.Column("widgets", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column("templates", api.models.model_helpers.GzipJsonType(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column(
            "created_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "updated_date", api.models.model_helpers.AwareDateTime(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["backend_uuid"],
            ["api_source.uuid"],
            name=op.f("fk_role_backend_backend_uuid_api_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["role.uuid"],
            name=op.f("fk_role_backend_role_uuid_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    with op.batch_alter_table("role_backend", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_role_backend_backend_uuid"), ["backend_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_role_backend_role_uuid"), ["role_uuid"], unique=False
        )


def downgrade():
    pass
