"""add personal access token

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-12

"""

import sqlalchemy as sa
from sqlalchemy_utils import UUIDType

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "personal_access_token" in inspector.get_table_names():
        # Already present: DBs baselined while 0001 still used live-metadata
        # create_all got this table from the models. Nothing to do.
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_access_token",
        sa.Column("user_uuid", UUIDType(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("token_prefix", sa.String(length=20), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("uuid", UUIDType(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_uuid"], ["user.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("token_hash", name="uq_personal_access_token_token_hash"),
    )
    with op.batch_alter_table("personal_access_token", schema=None) as batch_op:
        batch_op.create_index(
            "ix_personal_access_token_token_prefix",
            ["token_prefix"],
            unique=False,
        )
        batch_op.create_index(
            "ix_personal_access_token_token_type",
            ["token_type"],
            unique=False,
        )
        batch_op.create_index(
            "ix_personal_access_token_user_uuid",
            ["user_uuid"],
            unique=False,
        )
        batch_op.create_index(
            "ix_personal_access_token_user_uuid_token_type",
            ["user_uuid", "token_type"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personal_access_token")
    # ### end Alembic commands ###
