"""refactor copilot chats

Revision ID: 0d4a342f4c26
Revises: 5c8f2e91d0a3
Create Date: 2026-07-21 09:49:37.072245

"""

import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore
from api.models import model_helpers

# revision identifiers, used by Alembic.
revision = "0d4a342f4c26"
down_revision = "5c8f2e91d0a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "can_submit_marketplace",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    op.add_column(
        "vendor_app",
        sa.Column("mcp_servers", model_helpers.JSONType(), nullable=True),
    )
    op.rename_table("copilot_chat", "copilot_chat_old")

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    dialect = bind.dialect.name

    fk_constraints = inspector.get_foreign_keys("copilot_chat_old")
    ix_constraints = inspector.get_indexes("copilot_chat_old")
    with op.batch_alter_table("copilot_chat_old", schema=None) as batch_op:
        for fk in fk_constraints:
            if "copilot_chat" not in (name := fk["name"]):
                continue
            batch_op.drop_constraint(name, type_="foreignkey")
            batch_op.create_foreign_key(
                name.replace("copilot_chat", "copilot_chat_old"),
                fk["referred_table"],
                fk["constrained_columns"],
                fk["referred_columns"],
            )
        for ix in ix_constraints:
            if "copilot_chat" not in (name := ix["name"]):
                continue
            batch_op.create_index(
                name.replace("copilot_chat", "copilot_chat_old"),
                ix["column_names"],
                unique=ix["unique"],
            )
            batch_op.drop_index(name)

    op.create_table(
        "copilot_chat",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("content", model_helpers.GzipJsonType(), nullable=True),
        sa.Column("artifacts", model_helpers.GzipJsonLongType(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("last_opened", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.AwareDateTime(), nullable=True),
        sa.Column("updated_date", model_helpers.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_copilot_chat_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )

    with op.batch_alter_table("copilot_chat", schema=None) as batch_op:
        if dialect == "postgresql":
            batch_op.add_column(
                sa.Column(
                    "search_vector",
                    postgresql.TSVECTOR(),
                    sa.Computed("to_tsvector('simple', label)", persisted=True),
                    nullable=True,
                ),
            )
        batch_op.create_index(
            batch_op.f("ix_copilot_chat_user_uuid"), ["user_uuid"], unique=False
        )
        if dialect == "postgresql":
            batch_op.create_index(
                "ix_copilot_chat_search",
                ["search_vector"],
                unique=False,
                postgresql_using="gin",
            )
        if dialect == "mysql":
            batch_op.create_index(
                "ix_copilot_chat_search",
                ["label"],
                unique=False,
                mysql_prefix="FULLTEXT",
            )

    op.create_table(
        "copilot_messages",
        sa.Column("user_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("chat_uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("content", model_helpers.GzipJsonType(), nullable=True),
        sa.Column("searchable_content", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ai", "human", "summary", "system", "tool", name="message_role"),
            nullable=False,
        ),
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("created_date", model_helpers.DATETIME(fsp=3), nullable=True),
        sa.Column("updated_date", model_helpers.DATETIME(fsp=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_uuid"],
            ["copilot_chat.uuid"],
            name=op.f("fk_copilot_messages_chat_uuid_copilot_chat"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
            name=op.f("fk_copilot_messages_user_uuid_user"),
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )

    with op.batch_alter_table("copilot_messages", schema=None) as batch_op:
        if dialect == "postgresql":
            batch_op.add_column(
                sa.Column(
                    "search_vector",
                    postgresql.TSVECTOR(),
                    sa.Computed(
                        "to_tsvector('simple', searchable_content)", persisted=True
                    ),
                    nullable=True,
                ),
            )
        batch_op.create_index(
            "ix_user_chat_message",
            ["user_uuid", "chat_uuid", sa.literal_column("created_date DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_user_searchable_content",
            ["user_uuid", "chat_uuid", "role"],
            unique=False,
        )
        if dialect == "postgresql":
            batch_op.create_index(
                "ix_user_search_vector",
                ["search_vector"],
                unique=False,
                postgresql_using="gin",
            )
        if dialect == "mysql":
            batch_op.create_index(
                "ix_user_searchable_content_fulltext",
                ["searchable_content"],
                unique=False,
                mysql_prefix="FULLTEXT",
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("copilot_messages")
    op.drop_table("copilot_chat")

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    fk_constraints = inspector.get_foreign_keys("copilot_chat_old")
    ix_constraints = inspector.get_indexes("copilot_chat_old")
    with op.batch_alter_table("copilot_chat_old", schema=None) as batch_op:
        for fk in fk_constraints:
            if "copilot_chat_old" not in (name := fk["name"]):
                continue
            batch_op.drop_constraint(name, type_="foreignkey")
            batch_op.create_foreign_key(
                name.replace("_old", ""),
                fk["referred_table"],
                fk["constrained_columns"],
                fk["referred_columns"],
            )
        for ix in ix_constraints:
            if "copilot_chat_old" not in (name := ix["name"]):
                continue
            batch_op.create_index(
                name.replace("_old", ""),
                ix["column_names"],
                unique=ix["unique"],
            )
            batch_op.drop_index(name)

    op.rename_table("copilot_chat_old", "copilot_chat")
    op.drop_column("user", "can_submit_marketplace")
    # ### end Alembic commands ###
