import type { Widget } from "~/components/types";
import { uuidv4 } from "~/lib/utils";

function getHostname(url: string): string {
  try {
    return new URL(url).hostname || "Website";
  } catch {
    return "Website";
  }
}

/**
 * Builds the `iframe` custom-widget payload created when a user opens an external
 * link as an embedded page. Centralizes the shape so every entry point (copilot
 * external-link dialog, markdown widget, ...) stays in sync and stays typed.
 *
 * @param url - Page to embed; stored on `storage.html` and read by the Iframe widget.
 * @param source - Human label for where the widget originated, shown in the description.
 * @param innerTab - Optional dashboard inner-tab to place the widget on.
 */
export function buildIframeWidget(
  url: string,
  source: string,
  innerTab?: string,
): Widget {
  return {
    id: uuidv4(),
    name: getHostname(url),
    widgetId: "iframe",
    description: `Iframe for ${url}. Generated by ${source}`,
    type: "custom",
    storage: { html: url },
    ...(innerTab ? { innerTab } : {}),
  };
}
